### DISCUSSION TITLE
Run Prefect Server & Worker in a K8s Cluster

### DISCUSSION THREAD

**Discussion by benben2602** [PrefectHQ/prefect#11181] [Q&A]
Hello, I'm trying to run a prefect server and a worker in a local kind-k8s cluster by using the helm charts.

- First I successfully deployed the prefect-server by using:
`helm install prefect-server prefect/prefect-server --namespace=prefect`

- Next I've added a kubernetes WorkerPool named "k8s-test" at the prefect-dashboard.

- Finally I installed the worker with helm:
`helm install prefect-worker prefect/prefect-worker --namespace=prefect -f values.yaml` 

My values.yaml contains this:
```
fullnameOverride: prefect-worker
worker:
  apiConfig: server
  config:
    type: "kubernetes"
    workPool: "k8s-test"
  serverApiConfig:
    apiUrl: "http://prefect-server.prefect.svc.cluster.local"
```
When I check the pods with kubectl everything is running and look okay. But at the prefect-dashboard the worker-pool doesn't appear and the status is 'Not Ready'. There is no log message at the worker pod. It's just running.

Do you have an idea what's wrong with this simple example?
