### DISCUSSION TITLE
Block creation by yaml

### DISCUSSION THREAD

**Discussion by tmiyamon** [PrefectHQ/prefect#14620] [Ideas]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Describe the current behavior

Currently, Prefect's UI and CLI do not offer functionality to create Blocks from YAML or configuration files. This limitation makes it challenging to manage information efficiently.

### Describe the proposed behavior

Add functionality to create Blocks from configuration files in Prefect's UI or CLI.

### Example Use

```
prefect blocks load config.yaml 
```

The contents of config.yaml
```
string/test-string:
  value: test-value
sqlalchemy-connector/db-uri:
  connection_info:
    driver: postgresql+asyncpg
    database: test-db
    username: user
    password: password
    host: localhost
    port: "5432"
```

### Additional context

Consider adding an overwrite option when creating or updating Blocks. This feature would be useful during execution.
