### DISCUSSION TITLE
How to integrate Logfire with prefect?

### DISCUSSION THREAD

**Discussion by zzstoatzz** [PrefectHQ/prefect#16080] [Show and tell]
[WIP] will add color to this

1. Write some code with external loggers
```python
import logfire
from prefect import flow
from prefect.logging import get_run_logger

logfire.configure(console=False)  # Avoid duplicate logs

@flow
def log_flow():
    logger = get_run_logger()
    logger.error("Test message")

if __name__ == "__main__":
    log_flow()
```

2. Create a logging configuration (`logging.yaml`):
```yaml
handlers:
  logfire:
    level: 0
    class: logfire.LogfireLoggingHandler
    formatter: standard

loggers:
  prefect:
    level: "${PREFECT_LOGGING_LEVEL}"

  prefect.flow_runs:
    level: NOTSET
    handlers: [api, logfire]

  prefect.task_runs:
    level: NOTSET
    handlers: [api, logfire]
```

3. Run your code, setting the logging config path:
```bash
PREFECT_LOGGING_CONFIG_PATH=logging.yaml python main.py
```
