### DISCUSSION TITLE
what about add base_job_template.json in work queues?

### DISCUSSION THREAD

**Discussion by jsshizhan** [PrefectHQ/prefect#16166] [General]
every work queues have its own config

**Comment by leonkozlowski** [comment]
Variables can be used in your deployments (based on the work queue you are deploying to)
Some example variables in base job template
```yaml
"resources": {
  "limits": {
    "cpu": "{{ cpu_limit }}",
    "memory": "{{ memory_limit }}"
  },
  "requests": {
    "cpu": "{{ cpu_request }}",
    "memory": "{{ memory_request }}"
  }
````

As an example for a deployment in a lower environment I have lower memory limits than production

Dev deployment in `prefect.yaml`
```yaml
work_pool:
  name: k8s-work-pool
  work_queue_name: dev-k8s
  job_variables:
    image: "{{ build-image.image }}"
    memory_request: "1Gi"
    memory_limit: "1Gi"
```

Prod deployment in `prefect.yaml`
```yaml
work_pool:
  name: k8s-work-pool
  work_queue_name: prod-k8s
  job_variables:
    image: "{{ build-image.image }}"
    memory_request: "6Gi"
    memory_limit: "8Gi"
```

These variables make the base job template flexible
