### DISCUSSION TITLE
Pulling a private Git repo via prefect.yaml crashes Prefect worker

### DISCUSSION THREAD

**Discussion by TristanAmond** [PrefectHQ/prefect#16465] [Q&A]
I'm troubleshooting an issue deploying through prefect.yaml on Prefect managed infrastructure. I've created a simple flow testing the Discord webhook integration that I'm storing in a private Git repo. That flow runs successfully when deploying through python, but the flow instantly crashes when deploying through my prefect.yaml; the worker error log only shows a status code 1 exit. They're both deploying to the same worker that has prefect-github set up as a dependency, and they're accessing the private repo through a GitHubCredentials block.

I've tried a dozen different variations here, everything from moving the YAML file into the root directory to changing the default worker image. My best guess at this point is that the pathing is different when pulling the repo through the yaml file vs. the python script. I haven't found a way to explicitly set the path config seen in the Prefect UI when viewing a deployment; in the current iteration I've tried to fix this by setting the working directory, but that hasn't resolved the issue. I've also tried searching but haven't seen this specific configuration referenced before, so I hope fixing this helps more folks than just me. Sharing an example of my working python file and non-working yaml file below; any pointers would be greatly appreciated!

Project structure
```
top-level/               # Root repository
└── prefect/              # Prefect flows directory
    ├── prefect.yaml      # Deployment configuration (crashes when deployed)
    ├── discord_test.py   # Working flow (when deployed via Python)
```

successful python file deploy section
```
source = GitRepository(
                url="https://github.com/[username]/[repo].git",
                credentials=GitHubCredentials.load("github-credentials")
)
discord_test_flow.from_source(
                source=source,
                entrypoint="prefect/discord_test.py:discord_test_flow",
).deploy(
                name="python-discord-test",
                work_pool_name="[work pool]",
)
```

unsuccessful YAML file
```
# Generic metadata about this project
name: prefect
prefect-version: 3.1.6

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.git_clone:
    id: clone-step
    repository: https://github.com/[username]/[repo].git
    branch: main
    credentials: '{{ prefect.blocks.github-credentials.github-credentials }}'
- prefect.deployments.steps.set_working_directory:
    directory: '{{ clone-step.directory }}/prefect'

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: yaml-discord-test
  version: '1'
  tags:
  - test
  description: Discord webhook test flow
  schedule: {}
  entrypoint: discord_test.py:discord_test_flow
  parameters: {}
  work_pool:
    name: [work pool]
    work_queue_name: default
    job_variables: {}
  enforce_parameter_schema: true
  schedules: []
  concurrency_limit:
```
