### DISCUSSION TITLE
Flow run infrastructure exited with non-zero status code 255

### DISCUSSION THREAD

**Discussion by hongbo-miao** [PrefectHQ/prefect#17287] [Q&A]
I deployed Prefect successfully. Here are my deployment codes:
- [Prefect Server](https://github.com/hongbo-miao/hongbomiao.com/blob/54ad9d63ae9c47bdfc8d79dea86258f84653386b/kubernetes/argo-cd/applications/production-hm/prefect-server/argo-cd-manifests/hm-prefect-server-application.yaml)
- [Prefect Worker](https://github.com/hongbo-miao/hongbomiao.com/blob/54ad9d63ae9c47bdfc8d79dea86258f84653386b/kubernetes/argo-cd/applications/production-hm/prefect-worker/argo-cd-manifests/hm-prefect-worker-application.yaml)

Now I am trying to run a Prefect workflow. Here are my codes:

main.py

```py
import platform
from prefect import flow, get_run_logger

@flow
def print_platform() -> None:
    logger = get_run_logger()
    logger.info(f"Node: {platform.node()}")
    logger.info(f"Platform: {platform.platform()}")
    logger.info(f"Python Version: {platform.python_version()}")


if __name__ == "__main__":
    print_platform()
```

deploy.py

```py
import asyncio
from main import print_platform

async def deploy() -> None:
    await print_platform.deploy(
        name="hm-development-print-platform",
        work_pool_name="hm-work-pool",
        image="ghcr.io/hongbo-miao/hm-prefect-print-platform:latest",
        push=True,
    )

if __name__ == "__main__":
    asyncio.run(deploy())
```

pyproject.toml

```toml
[project]
name = "prefect-print-platform"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "prefect-client==3.2.7",
]

[dependency-groups]
dev = [
  "poethepoet==0.32.2",
  "pytest-cov==6.0.0",
  "pytest==8.3.4",
]

[tool.uv]
package = false

[tool.poe.tasks]
deploy = "python src/deploy.py"
```

When I run `uv run poe deploy`, I can see

```sh
Poe => python src/deploy.py
Successfully built image 
'ghcr.io/hongbo-miao/hm-prefect-print-platform:latest'
Successfully pushed image 
'ghcr.io/hongbo-miao/hm-prefect-print-platform:latest'
Successfully created/updated all deployments!

                            Deployments                             
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ Name                                         ┃ Status  ┃ Details ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ print-platform/hm-development-print-platform │ applied │         │
└──────────────────────────────────────────────┴─────────┴─────────┘

To schedule a run for this deployment, use the following command:

        $ prefect deployment run 
'print-platform/hm-development-print-platform'


You can also run your flow via the Prefect UI: https://prefect.hongbomiao.com/deployments/deployment/6790e4ac-d9fa-4c0c-8724-9de10660dc18
```

However, the job failed with

> Flow run infrastructure exited with non-zero status code 255.

![image](https://github.com/user-attachments/assets/39486532-82db-4105-a8d1-86c4013221cd)

Any help would be appreciate, thanks! ☺️
