### DISCUSSION TITLE
Configure PREFECT__USER_CONFIG_PATH in windows

### DISCUSSION THREAD

**Discussion by Sinha-Ujjawal** [PrefectHQ/prefect#3432] [Q&A] [answered]
I want to keep ```config.toml``` file as part of my code base. How can I configure **PREFECT__USER_CONFIG_PATH** in **windows**?

In my scenario, I have a config.toml file-

```toml
[logging]
PREFECT__LOGGING__FORMAT="[%(levelname)s] | %(asctime)s | %(name)s | %(message)s"
PREFECT__LOGGING__LEVEL="DEBUG"
```

I want to set **PREFECT__USER_CONFIG_PATH**, for that I have to give the absolute path for it to work. Ideally I should be giving relative path, right?

**Comment by Sinha-Ujjawal** [comment, marked as answer]
Sorry my bad, I resolved the issue. I was not reading the doc properly 
```toml
[logging]
format = "[%(levelname)s] | %(asctime)s | %(name)s | %(message)s"
level = "DEBUG"
```
