### DISCUSSION TITLE
Use your own postgreSQL database in prefect server

### DISCUSSION THREAD

**Discussion by Sinha-Ujjawal** [PrefectHQ/prefect#3700] [Q&A] [answered]
Hi,
Is there a way to use your own postgreSQL database instead of the one that comes with prefect server.

**Comment by zanieb** [comment, marked as answer]
Hi! You can change the config values to point to your own database.

```toml
    [server.database]
    host = "localhost"
    port = "5432"
    host_port = "5432"
    name = "prefect_server"
    username = "prefect"
    # set to "" to generate a random password each time the database starts
    password = "test-password"
    connection_url = "postgresql://${server.database.username}:${server.database.password}@${server.database.host}:${server.database.port}/${server.database.name}"
    volume_path = "${home_dir}/pg_data"
```

All the available options can be seen at https://github.com/PrefectHQ/prefect/blob/master/src/prefect/config.toml

Config precedence docs at https://docs.prefect.io/core/concepts/configuration.html#configuration-precedence
