### DISCUSSION TITLE
How to specify on-premises Server URL in Python core library?

### DISCUSSION THREAD

**Discussion by alexanderwiller** [PrefectHQ/prefect#3912] [Q&A]
When using the Python core library, how can the URL of the Prefect server be specified?

My goal is to register local workflows to an on-premises Prefect server. Even with much search, I haven't really found a way that seems 'right'.

If I am not mistaken, this affects both `LocalAgent().start()` and `Flow().register()`, as both need this information to reach the server.

What I have found are the environment variables `PREFECT__CLOUD__API` and `PREFECT__CLOUD__AGENT__AUTH_TOKEN` (which would be the next question - how to specify the token?). If I understand correctly, I could use these env variables even when not using the official CLI and they will be processed somewhere in the lib, but I am confused that at least the first one is very sparsely documented and that there doesn't seem to be an obvious way to set this programatically.

Is there something I am missing?

**Comment by joshmeek** [comment]
Hi @alex04103 yes you can set your server URL via the `PREFECT__CLOUD__API` env var (even though it has _cloud_ in the name it works for both the server and prefect cloud). You do not need to set an auth token as auth tokens are only used when communicating with Prefect Cloud.

So running this should work:

```
export PREFECT__CLOUD__API=your_server_address:here

...register flows...

...run agent...
```

You can also set this directly in your `~/.prefect/config.toml`. Prefect configuration between server and cloud works like a toggle. Running `prefect backend server` will by default use the server configuration variables however ultimately the `cloud.api` is the one used. 

```toml
backend = "cloud" # or "server"

[server]
host = "http://localhost"
port = "4200"
endpoint = "${server.host}:${server.port}"

[cloud]
api = "${${backend}.endpoint}" # so if backend == server this will use server.endpoint and if cloud will use cloud.endpoint
endpoint = "https://api.prefect.io"
```
