### DISCUSSION TITLE
How pass variables through Kubernertes Secrets?

### DISCUSSION THREAD

**Discussion by raffOps** [PrefectHQ/prefect#5381] [Q&A]
I would like to set secrets by passing them as environment variables with prefix PREFECT__CONTEXT__SECRETS for these secrets to be used within the kubernetes run config.

In the chart helm I put the following variables in the agent definition: 
```
agent:
  env:
      - name: PREFECT__CLOUD__AGENT__LABELS
        value: '["k8s"]'
      - name: GCP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: prefect-credentials
              key: gcp_service_account
      - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: prefect-credentials
              key: github_access_token
```
but returns an error saying mapping is not possible in that place. 

I'm using a local cluster created with k3d
