### ISSUE TITLE
Allow for something like list appending in the prefect.yaml to allow for combination of common tags from a definition and deployment specific tags.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10061]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

```yaml
definitions:
  tags: &common_tags
    - 'prefect-patterns'
    - 'subflow-patterns'

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: dep-task-wrapped
  version: 
  tags: *common_tags
```

If I want to combine common-tags with a specific tag for each deployment I would like to do something like this that combines common tags with deployment-sepecific tags:
```yaml
definitions:
  tags: &common_tags
    - 'prefect-patterns'
    - 'subflow-patterns'

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: dep-task-wrapped
  version: 
  tags: 
    <<: *common_tags
    - 'child'
```

### Describe the proposed behavior

You can't directly append items to a list using aliases in YAML, but there's a workaround. You can create another list and use both the alias and the new item to form the new list:

```yaml
tags: &common_tags
  - "remote"
  - "eks"

deployments:
- name: dep-task-wrapped
  version: 
  tags: 
    <<: *common_tags
    - 'specific-tag'
```
From ChatGPT:

In this YAML file, *common_tags is an alias for the list defined by tags. The << is a merge key, it takes a mapping and adds all of its entries into the current mapping. In this case, it appends the elements of common_tags list to tags of dep-task-wrapped deployment and then adds 'specific-tag'.

However, it's important to note that merge key (<<:) is officially not a part of YAML specification and works mostly with libraries that support it (like Ruby or some specific versions of PyYAML in Python).
