### ISSUE TITLE
Variables are not resolved in deployment job_variables

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#10071]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect variables do not seem to be correctly propagated to the `job_variables` section of a deployment when using `prefect deploy` and `prefect.yaml`. 

### Reproduction

Create a file named `flow.py` with the following:

```python3
import os

from prefect import flow

@flow(log_prints=True)
def main():
    print(f"FOO is {os.getenv('FOO')}")

if __name__ == "__main__":
    main()
```

Create a file named `prefect.yaml` with the following:

```yaml
# Welcome to your prefect.yaml file! You can you this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: variables
prefect-version: 2.10.17

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /Users/emilchristensen/github/examples/variables

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: foo
  entrypoint: flow.py:main
  work_pool:
    name: foo-process
    job_variables:
      env:
        FOO: "{{ prefect.variables.foo }}"
 ```

Create variable `foo` set to `bar` in UI, then check its value:

```shell
prefect variable inspect foo
```

Create a new work pool:
```shell
prefect work-pool create foo-process -t process
```

Deploy the flow:
```shell
prefect --no-prompt deploy -n foo
```

Create a flow run:
```shell
prefect deployment run 'main/foo'
```

Start a worker:
```shell
prefect worker start --pool 'foo-process'
```

### Error

```python3
FOO is {{ prefect.variables.foo }}
```

### Versions

```Text
Version:             2.10.17
API version:         0.8.4
Python version:      3.9.16
Git commit:          6d53d9b4
Built:               Thu, Jun 22, 2023 5:28 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```
