### ISSUE TITLE
Worker configuration in prefect.yaml

### ISSUE THREAD

**Issue by kasteph** [PrefectHQ/prefect#10172]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Worker configuration is currently only possible in the following ways:
- Prefect CLI commands
- Prefect Python API
- Prefect UI

### Describe the proposed behavior

A possibility of defining work pools and work queues via the `prefect.yaml` file.

### Example Use

In the `prefect.yaml`:

```yaml
prefect-version: 2.10.17
name: data-platform

build: null
push: null

pull: null

work_pools:
   - name: foo
      queues:
        - name: a
           priority: 1
        - name: b
           priority: 50
   - name: bar
      type: process
      queues:
        - name: c
           priority: 1
        - name: d
           priority: 50

```

### Additional context

It would be great if this could be captured via a canonical Prefect file such as the prefect.yaml instead of having to stitch this with shell scripts.
