### ISSUE TITLE
Prefect `on_cancellation` hook is not called when cancelling a flow during a task submitted to a task runner

### ISSUE THREAD

**Issue by PPPSDavid** [PrefectHQ/prefect#10195]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When trying to add an on_cancellation hook to a Prefect flow, I noticed that the cancellation hook is never called upon flow run cancellation.

### Reproduction
run the following flow code as a deployment, and cancel it mid-way from the local Prefect server UI:

```python3
import time
from prefect import flow, get_run_logger, task
from prefect.deployments import Deployment

@task
def sample_task():
    logger = get_run_logger()
    logger.info('Task running!')
    time.sleep(100)


def on_cancellation(flow, flow_run, state):
    logger = get_run_logger()
    logger.info('Sample log')
    print('called!')


@flow(on_cancellation=[on_cancellation], log_prints=True)
def sample_flow():
    sample_task.submit()


if __name__ == '__main__':
    deployment = Deployment.build_from_flow(
        flow=sample_flow,
        name="example-deployment", 
        version=1, 
        work_queue_name="demo",
        work_pool_name="default-agent-pool",
    )
    deployment.apply()
```

### Error
What I noticed from Prefect agent logs:

```python3
16:14:55.944 | INFO    | Flow run 'positive-ibis' - Created task run 'sample_task-0' for task 'sample_task'
16:14:55.945 | INFO    | Flow run 'positive-ibis' - Submitted task run 'sample_task-0' for execution.
16:14:55.989 | INFO    | Task run 'sample_task-0' - Task running!
16:15:10.314 | INFO    | prefect.agent - Found 1 flow runs awaiting cancellation.
16:15:10.355 | INFO    | prefect.agent - Killing process WIN-12A95KJ0HKG:31076 for flow run '72c2d34d-d355-4339-b785-c06925e4e2a5'...
^C16:15:10.370 | ERROR   | prefect.infrastructure.process - Process 'positive-ibis' exited with status code: 3221225786; Process was terminated due to a Ctrl+C or Ctrl+Break signal. Typically, this is caused by manual cancellation.
16:15:10.381 | INFO    | prefect.agent - Cancelled flow run '72c2d34d-d355-4339-b785-c06925e4e2a5'!
```

See the flow run is canceled but no mention of on_cancellation hooks

What I observed from the Prefect UI logs section: Neither the print statement nor the log statement produces any logs, meaning the cancellation hook is never actually executed.

### Versions

```Text
the latest pull of v 2.10.20 from conda
```

**Comment by zhen0** [comment]
Thanks for flagging @PPPSDavid

**Comment by serinamarie** [comment]
Hi @PPPSDavid, thanks for the issue!

It appears that the `on_cancellation` hook is sometimes not called upon cancellation, specifically, when submitting a task to a task runner using `.submit()`. I believe this is due to the fact that when reporting task run crashes, cancellation leads to a termination signal that doesn't seem to cause an exception during `wait_for_task_runs_and_report_crashes`, while it does in `report_flow_run_crashes`.

When we submit a task to a task runner:
https://github.com/PrefectHQ/prefect/blob/beedb2eef09fd994a3f3b915ced90d8e5f7ea333/src/prefect/engine.py#L1449-L1452

We begin the task run:

https://github.com/PrefectHQ/prefect/blob/beedb2eef09fd994a3f3b915ced90d8e5f7ea333/src/prefect/engine.py#L1539-L1549

We wait for and report task run crashes:
https://github.com/PrefectHQ/prefect/blob/beedb2eef09fd994a3f3b915ced90d8e5f7ea333/src/prefect/engine.py#L1822-L1828

We don't appear to get past line 1828 when cancelling from the UI in a flow during a task that was **submitted**. That's an issue we'll have to investigate further.

Without using `.submit()`, the `on_cancellation` hook is called correctly. In this case, I believe the current workarounds would be to use `.wait()` or `.result()` after submitting the task within the flow that has the cancellation hook: https://docs.prefect.io/2.11.3/concepts/task-runners/?h=submit#using-results-from-submitted-tasks

For example:
```python

@flow(on_cancellation=[on_cancellation], log_prints=True)
def sample_flow():
    future = sample_task.submit()
    future.result()
```

```python

@flow(on_cancellation=[on_cancellation], log_prints=True)
def sample_flow():
    future = sample_task.submit()
    future.wait()
```

**Comment by PPPSDavid** [comment]
Thanks, @serinamarie  for the investigation. A couple of follow-up questions:

1. If a task is run without submit(), it is my understanding that this task is run in-process without a task runner. Would the cancellation hook be called actually AFTER the task run completes Does that mean the cancellation action does not take effect immediately? 
2. In our use case, we have many large flow runs that depend on the submit() and wait_for functions to orchestrate parallel execution of tasks. See example below:
`
import time
from prefect import flow, get_run_logger, task
from prefect.deployments import Deployment

@task
def sample_task():
    logger = get_run_logger()
    logger.info('Task running!')
    time.sleep(20)


def on_cancellation(flow, flow_run, state):
    print('called!')


@flow(on_cancellation=[on_cancellation], log_prints=True)
def sample_flow():
    f1 = sample_task.submit()
    f2 = sample_task.submit(wait_for = [f1])
    f2.wait()



`

When trying to run this flow run with local process infrastructure, I noticed:
- When canceling during the first task run, the flow run process is killed immediately and the cancellation hook is not called
- When canceling during the second task run (the one that has wait() calls), **on_cancellation is called**, but it seems like the cancellation call does not terminate the flow run, but instead it waits for the current task run to finish. This seems unexpected, and caused a canceled flow run with all tasks completed:

`

12:17:21.652 | INFO    | Flow run 'prehistoric-macaque' - Created task run 'sample_task-0' for task 'sample_task'
12:17:21.653 | INFO    | Flow run 'prehistoric-macaque' - Submitted task run 'sample_task-0' for execution.
12:17:21.709 | INFO    | Flow run 'prehistoric-macaque' - Created task run 'sample_task-1' for task 'sample_task'
12:17:21.710 | INFO    | Flow run 'prehistoric-macaque' - Submitted task run 'sample_task-1' for execution.
12:17:21.715 | INFO    | Task run 'sample_task-0' - Task running!
12:17:41.742 | INFO    | Task run 'sample_task-0' - Finished in state Completed()
12:17:41.785 | INFO    | Task run 'sample_task-1' - Task running!
12:18:01.814 | INFO    | Task run 'sample_task-1' - Finished in state Completed()
12:18:01.834 | INFO    | Flow run 'prehistoric-macaque' - Running hook 'on_cancellation' in response to entering state 'Cancelling'
12:18:01.835 | INFO    | Flow run 'prehistoric-macaque' - Hook 'on_cancellation' finished running successfully

`

![image](https://github.com/PrefectHQ/prefect/assets/39285150/5ea969f8-a369-4ade-909e-3bdb56ad0e30)

**Comment by serinamarie** [comment]
> 1. If a task is run without submit(), it is my understanding that this task is run in-process without a task runner. Would the cancellation hook be called actually AFTER the task run completes Does that mean the cancellation action does not take effect immediately?

If I'm understanding your question correctly, it's that we check for flow run hooks in a few different places, but the `on_cancellation` hook is called here when a flow enters a `CANCELLING` state:

https://github.com/PrefectHQ/prefect/blob/16f46ca49838cbdb250d113bb149f13ca819302d/src/prefect/engine.py#L1926-L1933

When a task is submitted to a task runner, we do not hit this code upon flow cancellation. We might want to, or perhaps might want to change our existing implementation...

> When canceling during the second task run (the one that has wait() calls), `on_cancellation` is called, but it seems like the cancellation call does not terminate the flow run, but instead it waits for the current task run to finish. This seems unexpected, and caused a canceled flow run with all tasks completed

It's interesting that flow run cancellation waits for a task to complete in that case rather than cancelling immediately. It might be something where we'd want to check the task runner implementation and the engine 🤔 

Thanks for raising the issue! I would subscribe to #10367 for updates on this.

**Comment by taylor-curran** [comment]
Updated MRE:

```python

import time

from prefect import flow, get_run_logger, task, serve

@task
def my_task(seconds: int):
    time.sleep(seconds)


def on_cancellation(flow, flow_run, state):
    logger = get_run_logger()
    logger.info('Sample log')
    print('called!')


@flow(on_cancellation=[on_cancellation], log_prints=True)
def cancel_flow_submitted_tasks(sleep_time: int = 100):
    my_task.submit(sleep_time)

@flow(on_cancellation=[on_cancellation], log_prints=True)
def cancel_flow_not_submitted(sleep_time: int = 100):
    my_task(sleep_time)


if __name__ == "__main__":
    submitted_deploy = cancel_flow_submitted_tasks.to_deployment(name="submitted_deploy")
    # 16:58:54.764 | INFO    | prefect.runner - Found 1 flow runs awaiting cancellation.
    # 16:58:54.775 | ERROR   | prefect.flow_runs.runner - Process 30331 exited with status code: -15; This indicates that the process exited due to a SIGTERM signal. Typically, this is caused by manual cancellation.
    # 16:58:57.878 | INFO    | prefect.flow_runs.runner - Cancelled flow run '7d28621a-c8e8-454a-b4f3-40c7c275132c'!

    not_submitted_deploy = cancel_flow_not_submitted.to_deployment(name="not_submitted_deploy")
    # 16:53:37.979 | ERROR   | Task run 'my_task-0' - Crash detected! Execution was cancelled by the runtime environment.
    # 16:53:38.085 | ERROR   | Flow run 'tangible-scallop' - Crash detected! Execution was aborted by a termination signal.
    # 16:53:38.171 | INFO    | Flow run 'tangible-scallop' - Running hook 'on_cancellation' in response to entering state 'Cancelling'
    # 16:53:38.172 | ERROR   | Flow run 'tangible-scallop' - An error was encountered while running hook 'on_cancellation'

    serve(submitted_deploy, not_submitted_deploy)

```

**Comment by taylor-curran** [comment]
Updated MRE:

When task is not submitted:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/aae54562-b706-4dba-a055-5bbab81c62e3)



When task is submitted its still in running?

![image](https://github.com/PrefectHQ/prefect/assets/68969861/57e07bb7-259d-4067-8285-056deba7650b)


```yaml
# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: prefect
prefect-version: 2.13.4+26.g5d7c6d6ce.dirty

# build section allows you to manage and build docker images
build:
- prefect_docker.deployments.steps.build_docker_image:
    requires: prefect-docker>=0.3.1
    id: build-image
    dockerfile: auto
    image_name: taycurran/first-dep
    tag: latest

# push section allows you to manage if and how this project is uploaded to remote locations
push:

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /opt/prefect/prefect

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: dep-submitted
  version:
  tags: []
  description:
  entrypoint: cancel_not_working.py:cancel_flow_submitted_tasks
  parameters: {}
  work_pool:
    name: my-k8s-pool
    work_queue_name:
    job_variables:
      image: '{{ build-image.image }}'
  schedule:
- name: dep-not-submitted
  version:
  tags: []
  description:
  entrypoint: cancel_not_working.py:cancel_flow_not_submitted
  parameters: {}
  work_pool:
    name: my-k8s-pool
    work_queue_name:
    job_variables:
      image: '{{ build-image.image }}'
  schedule:
```

```python
import time

from prefect import flow, get_run_logger, task, serve

@task
def my_task(seconds: int):
    time.sleep(seconds)


def on_cancellation(flow, flow_run, state):
    logger = get_run_logger()
    logger.info('Sample log')
    print('called!')


@flow(on_cancellation=[on_cancellation], log_prints=True)
def cancel_flow_submitted_tasks(sleep_time: int = 100):
    my_task.submit(sleep_time)

@flow(on_cancellation=[on_cancellation], log_prints=True)
def cancel_flow_not_submitted(sleep_time: int = 100):
    my_task(sleep_time)


if __name__ == "__main__":
    cancel_flow_submitted_tasks(name="submitted_deploy")
    cancel_flow_not_submitted(name="not_submitted_deploy")
```
