### ISSUE TITLE
Allow for trigger definitions to be specified at the top level of prefect.yaml 

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#10223]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Triggers must be specified at the deployment level

### Describe the proposed behavior

Should be configurable at the prefect.yaml level

### Example Use

```
triggers:
  - enabled: true
    match:
      prefect.resource.id: prefect.flow-run.*
    expect:
      - prefect.flow-run.Completed
    match_related:
      prefect.resource.name: prefect.asd
      prefect.resource.role: deployment
```

### Additional context

we should ensure the default can be overridden. We should ensure delete / create behavior is preserved.
