### ISSUE TITLE
Add env option to `build_docker_image` build step

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect#10331]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The prefect deploy `build_docker_image` step does not support passing in an env variable. Exporting the variable prior to running `prefect deploy` or running a shell script to export the variable does not work either. For example, attempting to export the env var through the `run_shell_script` step results in this error `FileNotFoundError: [Errno 2] No such file or directory: 'export'`

### Describe the proposed behavior

There are cases where it would be necessary to have an env variable set prior to building the image. Expected behavior would be to have an option to pass an env var(s) directly. 

### Example Use

```
  - prefect_docker.deployments.steps.build_docker_image:
      id: build_image
      requires: prefect-docker>=0.3.0
      image_name: jsopkin/my-test-image
      tag: latest
      dockerfile: Dockerfile
      push: true
      env: {MY_VARIABLE: "my-value"}
```

### Additional context

This issue is referring to a use case where `DOCKER_BUILDKIT` needs to be set prior to building the Docker image
