### ISSUE TITLE
Allow deployment name to be used as a folder in S3

### ISSUE THREAD

**Issue by vishaalkk** [PrefectHQ/prefect#10362]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Given this `prefect.yaml`, when we do `prefect deploy`,  it pushes everything in the directory `prefect-main`

```yaml
# Welcome to your prefect.yaml file! You can you this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: dbt_runner_flow
prefect-version: 2.11.1

# build section allows you to manage and build docker images
build: null

definitions:
  work_pools:
    my_dbt_work_pool: &my_dbt_work_pool
      name: default-worker-pool
      work_queue_name:
      job_variables:
        task_definition_arn: ""
        cluster: stage-prefect
        vpc_id: ""
        launch_type: FARGATE
        family: prefect-v2-dbt
  # push section allows you to manage if and how this project is uploaded to remote locations
  actions:
    push_config: &push_config
      - prefect_aws.deployments.steps.push_to_s3: &push_c
          id: push-code
          requires: prefect-aws>=0.3.0
          bucket: prefect-storage-stage
          folder: "prefect-main/{{ flow.name }}"

  # pull section allows you to provide instructions for cloning this project in remote locations
    pull_config: &pull_config
      - prefect_aws.deployments.steps.pull_from_s3: 
          id: pull-code
          requires: prefect-aws>=0.3.0
          bucket: "{{ push-code.bucket }}"
          folder: "{{ push-code.folder }}"

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: dbt-runner
  id: flow
  version: null
  tags: []
  description: null
  entrypoint: flow.py:entrypoint_flow
  parameters: {}
  work_pool: *my_dbt_work_pool
  push: *push_config
  pull: *pull_config
  schedule: null
```

<img width="465" alt="image" src="https://github.com/PrefectHQ/prefect/assets/13641827/27c01da2-721f-43df-a79f-abd1e5996246">

### Describe the proposed behavior

Ideally, we would want to create nested directories -- in the case outlined above, we would want the deployment name to be a directory so that multiple deployments get pushed to their own directories. This can be achieved by hardcoding the name, but templating it would scale it up if we have multiple deployments in a given `prefect.yaml` file.

<img width="527" alt="image" src="https://github.com/PrefectHQ/prefect/assets/13641827/f486fb9c-1eb3-458f-903d-c930f3533fb7">
