### ISSUE TITLE
Block and variable references are not resolved in `prefect.yaml` outside of deploy steps

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#10388]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When blocks and/or variables are used to populate a field in `prefect.yaml` outside of `build`, `push`, or `pull`, the block or variable used is not resolved and the expected value is not inserted.

### Reproduction

Example `prefect.yaml`:

```yaml
prefect-version: 2.10.20
name: analyst-operations-qep-yaml # ex: position-pnl-pipeline-yaml

pull:
    - prefect.deployments.steps.git_clone:
        repository: https://github.com/***/***-***.git
        branch: "main"
        credentials: "{{ prefect.blocks.github-credentials.sra-service-account }}"

definitions:
    work_pools:
        ecs_work_pool: &ecs_work_pool
            name: "{{ prefect.blocks.string.ecs-work-pool }}"
            work_queue_name: default
            job_variables:
                image: "*****.dkr.ecr.us-east-2.amazonaws.com/py310-base:0.0.3" 

        ny4_work_pool: &ny4_work_pool
            name: "{{ prefect.blocks.string.ny4-work-pool }}"
            work_queue_name: default
            job_variables:
                image: "****.dkr.ecr.us-east-2.amazonaws.com/py310-base:0.0.3" 

deployments:
    - name: Set QEP Status
      description: null # optional
      entrypoint: QEP/setQEPstatus.py:set_qep_status 
      work_pool: *ecs_work_pool
      parameters: {} # optional parameters overrride here
      schedule:
        cron: "1 19 * * *"
        timezone: "America/Chicago"
```

### Error

From CLI:

This deployment configuration references work pool '{{ prefect.blocks.string.ecs-work-pool }}' which does not exist. This means no worker will be able to pick up its runs. You can create a work pool in the Prefect UI.

### Versions

```Text
Version:             2.11.3
API version:         0.8.4
Python version:      3.10.6
Git commit:          3a400865
Built:               Thu, Aug 3, 2023 3:24 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```
