### ISSUE TITLE
typo in gcp recipe

### ISSUE THREAD

**Issue by jakekaplan** [PrefectHQ/prefect#10441]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The gcs recipe yaml is referencing `prefect.deployment` instead of `prefect.deployments`

### Reproduction

```python3
prefect init --recipe gcs
```
```


### Error

```python3
push:
- prefect_gcp.deployment.steps.push_to_gcs:
    id: push_code
    requires: prefect-gcp>=0.4.3
    bucket: aaa
    folder: prefect

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect_gcp.deployment.steps.pull_from_gcs:
    id: pull_code
    requires: prefect-gcp>=0.4.3
    bucket: '{{ push_code.bucket }}'
    folder: '{{ pull_code.folder }}'
```
```


### Versions

```Text
Version:             2.11.4+2.g249fd3e13.dirty
API version:         0.8.4
Python version:      3.11.0
Git commit:          249fd3e1
Built:               Fri, Aug 18, 2023 10:25 AM
OS/Arch:             darwin/x86_64
Profile:             prod-test
Server type:         cloud
```
