### ISSUE TITLE
Prefect deploy to target all deployments for a given entrypoint

### ISSUE THREAD

**Issue by mousetree** [PrefectHQ/prefect#10459]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When using `prefect.yaml` and `prefect deploy` there are only two ways of deploying (case specific to running within CI):

1. `prefect --no-prompt deploy -n my_deployment_1`. This deploys the named deployment called `my_deployment_1`
2. `prefect --no-prompt deploy --all`. This deploys all deployments found in the deployments section of `prefect.yaml`.

Let's assume we have two flows `flows/buy.py` and `flows/sell.py` and multiple deployments:

```yaml
deployments:
  - name: buy_google
    entrypoint: flows/buy.py:buy_stock
    parameters: { stock: 'GOOG' }
    work_pool: *work-pool-1
  - name: buy_apple
    entrypoint: flows/buy.py:buy_stock
    parameters: { stock: 'AAPL' }
    work_pool: *work-pool-1
  - name: sell_tesla
    entrypoint: flows/sell.py:sell_stock
    parameters: { stock: 'TSLA' }
    work_pool: *work-pool-1
```

During the CI process, we detect that the file `flows/buy.py` has changed and we want to re-deploy all deployments that reference it. Right now the only option is to re-deploy ALL flows (using option 1 above) as there is no command line option to deploy all deployments with a specific entrypoint or file.

### Describe the proposed behavior

The `prefect deploy` CLI should allow you to specify a file name or entrypoint such that it filters the list of deployments in `prefect.yaml` and only deploys those.

### Example Use

```
prefect --no-prompt deploy flows/buy.py:buy_stock
```

or 

```
prefect --no-prompt deploy --entrypoint flows/buy.py:buy_stock
```

or

```
prefect --no-prompt deploy flows/buy.py
```

### Additional context

This worked well in Prefect 1 with `prefect register` or when doing `Deployment.build_from_file` in Python. Both seem to have been deprecated.
