### ISSUE TITLE
PREFECT_API_KEY not secured in k8s flow run containers

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#10716]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When starting a flow-run in kubernetes, the `PREFECT_API_KEY` variable is passed as an environment variable in plain text.
This is a security concern.

### Describe the proposed behavior

Workers allow referencing a key from secretkeyRef - this should be passed as a similar reference to the child flow instead of in plain text.

### Example Use

A worker might reference the key in a secure way like :
```
        - name: PREFECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: prefect-api-key
              key: key
```

I propose this gets passed in to the base job template if it exists instead of passing this to the flow-run:
```
        - name: PREFECT_API_KEY
          value: <redacted>
```

### Additional context

I believe this is occurring when environment variables are being assigned to the job template before the pod is spun up? 
https://github.com/PrefectHQ/prefect-kubernetes/blob/main/prefect_kubernetes/worker.py#L311C1-L313C10
