### ISSUE TITLE
Scheduler fails to update infra overrides on previously runs when deployment is changed

### ISSUE THREAD

**Issue by StephenRobin** [PrefectHQ/prefect#10863]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When a deployment's infra overrides are updated, previously scheduled flow runs don't get updated to use the new overrides, unless I also update the schedule.

### Reproduction
I have this prefect.yaml:

```yaml
name: stephens-test-flows
prefect-version: 2.11.0

deployments:
- name: "test"
  tags:
   - Demo project
  schedule:
    cron: 0 8 * * 1-5
    timezone: Europe/London
  entrypoint: "projects/stephen-test/hello.py:hello"
  work_pool: 
    name: "testpool"
    job_variables:
      image: "registry.redacted.com/redacted/stephen-test:1.0.83"
      memory_limit: 1Gi
```
I deploy this to the prefect server with `prefect deploy --all`

The next three runs are created, as I would expect given my settings.

I update the `prefect.yaml` to change the image to `stephen-test:1.0.85`

I deploy again using  `prefect deploy --all`

The Prefect UI shows the deployment now has the correct infra overrides. However, when the previously scheduled flows are executed in K8s they still use the old image. I expected them to use the new image.

Workaround is to change the schedule and then change it back again.

### Versions

```Text
Version:             2.10.20
API version:         0.8.4
Python version:      3.10.9
Git commit:          08326f42
Built:               Fri, Jul 7, 2023 3:22 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server

The server is running the image `prefecthq/prefect:2.13.1-python3.11`
```
