### ISSUE TITLE
Resolve Keys in Block References in prefect.yaml

### ISSUE THREAD

**Issue by bjarneschroeder** [PrefectHQ/prefect#10930]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I'm currently solving #10388. While doing so, I noticed that I can only insert the full content of the `value` field of a block.

### Describe the proposed behavior

It might be nice to be able to reference a keypath in Blocks which store JSON-like or as dict parseable content.

### Example Use

Lets say I have a JSON Block named `json-block` specifying some deployment info with the following content:

```json
{
  "name": "nice-work-pool",
  "work-queues": ["wq1", "wq2"],
  "job-vars": {
     "image": "cool-image"
   }
}
```

I think it would be cool to be able to reference the keys and get their values in `prefect.yaml`. One could use `value` as a special key to indicate a keypath. `prefect.utilities.collections.get_from_dict` also made me realize that there is already functionality to get list-values as well.

```yaml
# prefect.yaml

...
deployments:
   - name: first-deployment
     ...
     work_pool:
       name: "{{ prefect.blocks.json.json-block.value.name }}"  # nice-work-pool
       work_queue_name: "{{ prefect.blocks.json-block.value.work-queues[1]"  # wq2
       ...
     job_variables: "{{ prefect.blocks.json-block.value.job-vars }}" # {"image": "cool-image"}
```

### Additional context

I actually wrote already some code which implements the proposed behavior. But I thought it might deviate too much from the fix for #10388. So I wanted ask first, if the feature makes sense. I would also have to implement the same behavior for Variables, but would be happy to do so. ☺️
