### ISSUE TITLE
Add automations to prefect.yaml for deployments

### ISSUE THREAD

**Issue by sra-mitch** [PrefectHQ/prefect#10978]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, automations on prefect cloud are only able to be set using the UI. It is time consuming and difficult to view all of the automations on the prefect cloud UI. 

### Describe the proposed behavior

Prefect automations will be able to be deployed via the prefect.yaml file for each of the deployments in the file. A user would have the same options which are visible on the UI, or be able to add a deployment to an existing automation (think a generic retry automation).

### Example Use

A user would create a depoyment within their prefect.yaml 

```  
   - name: Test-Deployment
      description: null
      entrypoint: test.py:test_func
      work_pool: *default_work_pool
      parameters: {
       }
      schedule:
          cron: 2 9 * * 1-5
          timezone: "America/Chicago" 
         automations:
          trigger: Flow run state
          state: ['Failed' , 'Crashed', 'TimedOut']
          action:
               notification:
                    block: test-slack-webhook

```
