### ISSUE TITLE
N events emitted in close succession that should trigger n action executions only trigger one.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#11199]
N events emitted in close succession that should trigger n action executions only trigger one.

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

N events emitted in close succession that should trigger n action executions only trigger one.

### Reproduction

`emit.py` - the script that will emit three events
```python

from prefect.events import emit_event

def emit_three_events():
    for _ in range(3):
        emit_event(event="external.resource.pinged", resource={"prefect.resource.id": "my.external.resource"})

if __name__ == "__main__":
    emit_three_events()
```
`script.py` a dummy flow
```
from prefect import flow

@flow
def tay():
    print("Hello world")
    
if __name__ == "__main__":  
    tay()
```
`prefect.yaml` - which links the event emission and script execution via an automation
```
# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: tay
prefect-version: 2.14.5

# build section allows you to manage and build docker images
build:

# push section allows you to manage if and how this project is uploaded to remote locations
push:

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /Users/willr/repos/tay

# the deployments section allows you to provide configuration for deploying flows (will need some alterations, WR happy to pair)
deployments:
- name: tay
  version:
  tags: []
  description:
  entrypoint: script.py:tay
  parameters: {}
  work_pool:
    name: noah
    work_queue_name:
    job_variables: {}
  schedule:
  triggers:
  - enabled: true
    match:
      prefect.resource.id: my.external.resource
    expect:
    - external.resource.pinged
    name: tay__automation_1
```

Apply the deployment yaml, run the emit script, and see the error. for confirmation, here is the automation trigger that is created on deployment apply

```
{
  "match": {
    "prefect.resource.id": "my.external.resource"
  },
  "match_related": {},
  "after": [],
  "expect": [
    "external.resource.pinged"
  ],
  "for_each": [],
  "posture": "Reactive",
  "threshold": 1,
  "within": 0
}
```

### Error

Three events are emitted but only one flow run is scheduled.

### Versions

```Text
Version:             2.14.5
API version:         0.8.4
Python version:      3.11.5
Git commit:          a4a313cd
Built:               Thu, Nov 16, 2023 3:32 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```
