### ISSUE TITLE
`run_shell_script` deployment step does not understand the pipe character (`|`)

### ISSUE THREAD

**Issue by rmnvncnt** [PrefectHQ/prefect#11287]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Following the ECR build example available [here](https://prefecthq.github.io/prefect-aws/ecs_guide/#Optional-Next-Steps), I came up with the following step in my `prefect.yaml` file : 
```
push:
- prefect.deployments.steps.run_shell_script:
    id: ecr-auth-step
    script: aws ecr get-login-password --region eu-west-2 --profile test-test-test | docker login --username AWS --password-stdin 12345678910.dkr.ecr.eu-west-1.amazonaws.com
    stream_output: true
```
Which then fails silently with the following output : 
```
Running deployment push steps...
 > Running run_shell_script step...

Unknown options: |,docker,login,--username,AWS,--password-stdin,12345678910.dkr.ecr.eu-west-1.amazonaws.com
```

### Reproduction

The example [here](https://prefecthq.github.io/prefect-aws/ecs_guide/#Optional-Next-Steps) with an existing AWS account will probably break.

### Versions

```Text
Version:             v2.14.6
API version:         0.8.4
Python version:      3.10.4
Git commit:          b99932a4
Built:               Wed, Nov 22, 2023 3:19 PM
OS/Arch:             darwin/arm64
Profile:             testing
Server type:         server
```

### Additional context

A deployment step that fails should trigger an error IMHO.
