### ISSUE TITLE
Unable to serve Prefect UI behind reverse proxy when using URL prefix

### ISSUE THREAD

**Issue by hozn** [PrefectHQ/prefect#11472]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Our environment restricts us to a single domain name / IP address / port (443) for all of our services.  We are unable to get prefect UI to be correctly served by when using a prefix (e.g. https://example.com/prefect ) using nginx reverse proxy, though by all accounts this is more general than nginx.

Note: this appears to be the same issue expressed by this closed issue #109 -- and referenced by the unanswered question/discussion: https://github.com/PrefectHQ/prefect/discussions/5376

Despite setting env vars (`PREFECT_UI_API_URL`) to the correct path, the UI will attempt to load assets without the correct prefix.

![image](https://github.com/PrefectHQ/prefect/assets/391939/01813198-1e3d-4742-a5c1-04f5db0c2614)

### Reproduction

```conf
# nginx.conf
location /prefect/ {
    include proxy_params;  # Header, etc.
    proxy_pass http://prefect-server:4200;
}
```

```yaml
# docker-compose.yml
services:
  prefect-server:
    # snip
    entrypoint: [ "prefect", "server", "start" ]
    environment:
      # Instruct the JS UI how to connect to the UI server
      - PREFECT_UI_API_URL=https://localhost/prefect/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
```

### Error

Error is visible in the attached screenshot image.  Error indicates that the prefix was not respected.

### Versions

```Text
2.14.3
```

### Additional context

This is also a Slack discussion: https://prefect-community.slack.com/archives/CL09KU1K7/p1695828648656779
