### ISSUE TITLE
The `prefect deploy` command and prefect.yaml file should support multiple deployment schedules

### ISSUE THREAD

**Issue by TheoBabilon** [PrefectHQ/prefect#12092]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi team,

I'm trying to add multiple schedules to one of my deployments (through `prefect.yaml` file within my project).

When only providing one schedule through the `schedule` directive, everything works fine:
```yaml
deployments:
- name: "my-deployment-test"
  schedule:
    cron: "15 3 * * *"
    timezone: "Europe/Zurich"
    active: true
  entrypoint: my_entrypoint.py:my_flow_fn
  work_pool:
    name: "dev-process-pool"
    work_queue_name: null
```

Running `prefect --no-prompt deploy` will work and I will see my schedule displayed in the UI.

However (using prefect `2.16` on both server and client side), when adding multiple schedules as seen in the documentation:
```yaml
deployments:
- name: "my-deployment-test"
  schedules:
    - cron: "15 3 * * *"
      timezone: "Europe/Zurich"
      active: true
    - cron: "0 7 * * *"
      timezone: "Europe/Zurich"
      active: true
  entrypoint: my_entrypoint.py:my_flow_fn
  work_pool:
    name: "dev-process-pool"
    work_queue_name: null
```

Running `prefect --no-prompt deploy` will work fine (no error), but looking into the UI I don't see any schedule for my deployment, which is also confirmed by the cli command `prefect deployment schedule ls xxxxx` which returns an empty table.

I'm pretty sure I'm doing something wrong considering the multiple schedule has just been released in 2.16.0 but I can't figure out what from looking at the documentation.

### Reproduction

```python3
prefect --no-prompt deploy
```

### Versions

```Text
2.16.0
```
