### ISSUE TITLE
Prefect cli deploy doesnt seem to work on latest version

### ISSUE THREAD

**Issue by pvbhanuteja** [PrefectHQ/prefect#12148]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

(prefect) [opc@instance-20240301-1934 infb-]$ prefect deploy --all 
Deploying all flows with an existing deployment configuration...
Deploying  INFB Daily                   
usage: prefect [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
               [--auth_host_port [AUTH_HOST_PORT ...]]
               [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
prefect: error: unrecognized arguments: deploy --all
(prefect) [opc@instance-20240301-1934 infb]$ prefect --version
2.16.1

It is able to identily my local prefect.yaml file but thorws this issue for some reason.

my yaml file 

```yaml
# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: infb-scrape
prefect-version: 2.16.1

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /home/opc/prefect/infb

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: '[yt_infb] INFB Daily'
  version: null
  tags: []
  description: null
  entrypoint: main.py:main_flow
  parameters: {
    "frequency": "day"
  }
  work_pool:
    name: test-work-pool
    work_queue_name: null
    job_variables: {}
  schedules:
  - cron: 0 16 * * *
    timezone: Asia/Kolkata

- name: '[yt_infb] INFBt'
  version: null
  tags: []
  description: null
  entrypoint: main.py:main_flow
  parameters: {
    "frequency": "week"
  }
  work_pool:
    name: test-work-pool
    work_queue_name: null
    job_variables: {}
  schedules:
  - cron: 0 8 * * 5
    timezone: Asia/Kolkata

- name: '[yt_infb] INFB'
  version: null
  tags: []
  description: null
  entrypoint: main.py:main_flow
  parameters: {
    "frequency": "month"
  }
  work_pool:
    name: test-work-pool
    work_queue_name: null
    job_variables: {}
  schedules:
  - cron: 0 0 1 * *
    timezone: Asia/Kolkata
```

### Reproduction

```python3
(prefect) [opc@instance-20240301-1934 infb-]$ prefect deploy --all 
Deploying all flows with an existing deployment configuration...
Deploying  INFB Daily                   
usage: prefect [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
               [--auth_host_port [AUTH_HOST_PORT ...]]
               [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
prefect: error: unrecognized arguments: deploy --all
(prefect) [opc@instance-20240301-1934 infb]$ prefect --version
2.16.1

It can identify my local prefect.yaml file but throws this issue for some reason.
```

### Versions

```Text
2.16.1
```
