### ISSUE TITLE
Unable to Access Prefect Web UI: Docker Container Port Mapping Issue

### ISSUE THREAD

**Issue by seabnavin19** [PrefectHQ/prefect#12395]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I have set up a prefect server in a docker container but seems I can not access prefect server via my local computer 

### Reproduction

I setup a dockerfile for prefect 
```
FROM prefecthq/prefect:2-python3.11
RUN apt-get update
RUN apt-get update && apt-get install -y gnupg2
RUN apt-get install -y curl apt-transport-https
WORKDIR /prefect-docker
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
```
And this is my docker compose file to run prefect server
```
version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefectDatabase
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    profiles: ["orion"]

  ### MinIO for flow storage
  minio:
    image: minio/minio
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#2023
    command: server --console-address ":9001" /data
    profiles: ["agent"]



  orion:
    build: .
    container_name: prefect_ui
    restart: always
    volumes:
      - prefect:/root/.prefect
    #deploy and apply flow
    entrypoint: ["prefect", "server", "start"]
    environment:
      - DB_HOST=database
      - DB_USER=root
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefectDatabase
   
    ports:
      - 4200:4200
    profiles: ["orion"]
```
Then i run the application use this cmd
```
docker compose up database orion
```
This is what i got in my terminal
```
mlopsseries-database-1  | 
mlopsseries-database-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
mlopsseries-database-1  | 
mlopsseries-database-1  | 2024-03-23 09:44:38.460 UTC [1] LOG:  starting PostgreSQL 14.1 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
mlopsseries-database-1  | 2024-03-23 09:44:38.460 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mlopsseries-database-1  | 2024-03-23 09:44:38.460 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mlopsseries-database-1  | 2024-03-23 09:44:38.461 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mlopsseries-database-1  | 2024-03-23 09:44:38.463 UTC [21] LOG:  database system was shut down at 2024-03-23 09:44:22 UTC
mlopsseries-database-1  | 2024-03-23 09:44:38.465 UTC [1] LOG:  database system is ready to accept connections
prefect_ui              | 
prefect_ui              |  ___ ___ ___ ___ ___ ___ _____ 
prefect_ui              | | _ \ _ \ __| __| __/ __|_   _| 
prefect_ui              | |  _/   / _|| _|| _| (__  | |  
prefect_ui              | |_| |_|_\___|_| |___\___| |_|  
prefect_ui              | 
prefect_ui              | Configure Prefect to communicate with the server with:
prefect_ui              | 
prefect_ui              |     prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
prefect_ui              | 
prefect_ui              | View the API reference documentation at http://127.0.0.1:4200/docs
prefect_ui              | 
prefect_ui              | Check out the dashboard at http://127.0.0.1:4200
prefect_ui              | 
prefect_ui              | 
prefect_ui              | 
```
But I can not access prefect via my computer localhost
**Note This work with the older version but in docker-compose i put ["prefect orion start"] instead

### Error

I can not access to prefect UI via localhost

### Browsers

- [X] Chrome
- [x] Firefox
- [X] Safari
- [x] Edge

### Prefect version

```Text
prefect==2.16.2
```

**Comment by wakatara** [comment]
@seabnavin19 

I do not think this is a Prefect issue, but a docker one (disclaimer: I am _no_ docker expert). I have the following working locally and on a very beefy server. Perhaps the bridge network stanza needs to be in there for you? I've also got a worker in this setup but it all works together quite well. In my postgres setup I had originally loaded variables for pg via a .env variable but left in the commented out line for you in case it's non-obvious.

```yaml
version: "3.9"
services:
  server:
    image: prefecthq/prefect:2.16.6-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
      - /data/staging:/data/staging
    entrypoint: ["/bin/bash", "-c"]
    environment:
      # - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_HOST=127.0.0.1
      # - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////root/.prefect/prefect.db
      - EXTRA_PIP_PACKAGES=astropy prefect-sqlalchemy psycopg2-binary datetime httpx
    command: ["prefect server start --host 0.0.0.0"]
    ports:
      - "4200:4200"

...

networks:
  prefect-network:
    driver: bridge
```

I had this also working using postgres instead of sqlite but if you add that in, make sure you put in a db container obviously. but should work fine. This definitely exposes the prefect server on port 4200 and between other services like the worker container and db.

lemme know how it goes.
