### ISSUE TITLE
Duplicated local logs from prefect

### ISSUE THREAD

**Issue by DbCrWk** [PrefectHQ/prefect#12518]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This issue sits between a "bug" and something that needs a workable pattern. If have a large python package that centralizes a wide variety of functionality. I'm working on integrating `prefect` into this package to run certain workflows that currently just run as python scripts.

In this package, we have a central logging utility. We use that logging utility everywhere and I would like to keep that pattern consistent in the codebase. Even if I am not using `prefect` to do something, if `prefect` is included in the import chain somewhere, I end up with duplicate logs.

There have been previous issues and posts that document similar use cases:
 - #7851
 - #11173
 - #3524
 - [Discourse 3543](https://discourse.prefect.io/t/duplicate-logs-in-ui/3543)

However, some of these are old, unanswered, or do not give authoritative resolution. I would consider this behavior a bug because `prefect` should not be taking over logs especially if not in a `prefect` context. Either way, it would be helpful to have a workaround or clarification on how to remove these duplicate logs.

In prefect cloud, I only see one set of log statements, as desired. This is for logs in the runtime.

### Reproduction
Say, I have a file called `log.py`:
```python
import logging
from prefect.settings import (
    PREFECT_LOGGING_EXTRA_LOGGERS,
    update_current_profile,
)

logger = logging.getLogger("foo")
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)
logger.addHandler(console_handler)

update_current_profile({PREFECT_LOGGING_EXTRA_LOGGERS: "foo"})
```

And if I have another file called `task.py`:
```python
from log import logger

logger.info("Hello")
```

I will see *two* log statements when I run `python task.py`. If I drop the `prefect` import or use the run logger from `prefect` for logging, then this does not happen, but I may not be running `task.py` in a `prefect` context.

### Error

```python3
2024-04-01 09:37:02 INFO     Hello 
09:37:02.173 | INFO    | foo - Hello
```

### Versions

```Text
2.16.8
```

**Comment by abizer** [comment]
I am facing this issue as well. Importing prefect into my application with my own logging configured leads to duplicate logs in the console.

**Comment by zsio** [comment]
I have the same question.

**Comment by cicdw** [comment]
OK I figured this out, but the UX is quite annoying to deal with; the problem is that the extra logger is propagating each log record down to the root logger and so you're getting your `StreamHandler` + the root logger's `PrefectConsoleHandler`, causing log duplication.

The solution as of this moment is to provide a _completely custom_ `logging.yml` file and set

```yaml
loggers:                                                                                                                                                                                                                  
    prefect.extra:                                                                                           
        level: "${PREFECT_LOGGING_LEVEL}"                                                                
        handlers: [api]                                                                                  
        propagate: false  # <----- this is the key piece of config
```

The problem with this is that you have to _completely recreate_ the entire Prefect `logging.yml` file in order to preserve the Prefect logging configuration, which is really annoying for such a simple thing! 

So the solution in my opinion is to allow you to configure this field through an environment variable. I actually think I want to take this a step further and make the **default** value of this field be `false`, because I can't think of why you would _want_ the duplication if you're taking over configuration already.

Will open a PR, feel free to comment here if you disagree with my default -- either way, in the next release you'll be able to configure this transparently.
