### ISSUE TITLE
Docker image build step: Allow multiple image tags

### ISSUE THREAD

**Issue by sakce** [PrefectHQ/prefect#12934]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

```
build:
- prefect_docker.deployments.steps.build_docker_image:
    id: build_image
    requires: prefect-docker>=0.3.0
    image_name: <>.dkr.ecr.eu-west-1.amazonaws.com/prefect-rocks
    tag: latest
    dockerfile: auto
    platform: linux/amd64
    push: true
```

The `tag` field allows for a single image tag. If we wanted to tag with the build version and the `latest` tag we'd probably have to add another step to this deployment process.

### Describe the proposed behavior

```
build:
- prefect_docker.deployments.steps.build_docker_image:
    id: build_image
    requires: prefect-docker>=0.3.0
    image_name: <>.dkr.ecr.eu-west-1.amazonaws.com/prefect-rocks
    tags: [
        latest,
        0.1.8
    ]
    dockerfile: auto
    platform: linux/amd64
    push: true
```

Allow for multiple tags. Alternatively, allow both `tag` and `tags` field, in case having a field in plural for a single value might be confusing.

### Example Use

If `push: true` and we potentially have multiple deployments of the same flow, but with a different set of configs (i.e. for different platforms) or if we wanted the image to also have the `latest` tag next to the version build.
