### ISSUE TITLE
Add Container definitions to job variable / add awslogs-stream-prefix

### ISSUE THREAD

**Issue by sra-mitch** [PrefectHQ/prefect#13028]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, prefect does not support adding the job configuration below and is not passed into the register task definition. I would expect that all of the following would be passed into the ecs register task definition. 

The reason for this is that when running multiple flows, the register task definition the follow error would occur.

```
Flow run could not be submitted to infrastructure: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Too many concurrent attempts to create a new revision of the specified family.
```

```
    ecs_work_pool: &ecs_work_pool
        name: ecs-worker-pool
        work_queue_name: default
        job_variables:
          containerDefinitions:
            - logConfiguration:
                logDriver: awslogs
                options:
                  awslogs-group: prefect
                  awslogs-region: us-west-2
                  awslogs-create-group: true
                  awslogs-stream-prefix: My Flow Name
```

The work around to this was to explicitly include the family name as well as name within the job_variables as shown below:

```
        ecs_work_pool: &ecs_work_pool
            name: ecs-worker-pool
            work_queue_name: default
            job_variables:
              name: My Flow Name
              image: "xxxxxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com/py310:1.0.1"
              cpu: 4096
              memory: 9216
              family: my-flow
```

After discussion with Jake Kaplan, the following snips were found regarding the above:

```
        if configuration.configure_cloudwatch_logs:
            container["logConfiguration"] = {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "prefect",
                    "awslogs-region": region,
                    "awslogs-stream-prefix": configuration.name or "prefect",
                    **configuration.cloudwatch_logs_options,
                },
            }
```

then configuration.name is set as `self.name = self.name or flow_run.name`

### Describe the proposed behavior

The expected behavior is that when the `awslogs-stream-prefix` or `containerDefinitions` fields are provided in the prefect.yaml, all fields are passed onto the flow and ecs task creation.

### Example Use

Add the information to prefect.yaml to have further configuration of their jobs and prevent errors or cases where they may not want to publish new task definitions each time.
