### ISSUE TITLE
`push_project_to_s3` is not working with credentials stored in a prefect block

### ISSUE THREAD

**Issue by uuazed** [PrefectHQ/prefect#13038]
I've created a new project using the docker-s3 template. The credentials of my AWS service account are stored in a prefect block. According to the [prefect project tutorial](https://docs.prefect.io/latest/concepts/projects/#the-push-section), this is the recommended setup. This is the push section in my deployment.yaml :

```
push:
  - prefect_aws.projects.steps.push_project_to_s3:
        requires: "prefect-aws>=0.3.1"
        bucket: "prefect-..."
        folder: somefolder
        credentials: "{{ prefect.blocks.aws-credentials.prod }}"
```

When initiating a deploy via `prefect deploy --name ... `, the step fails with 
``TypeError: Session.client() got an unexpected keyword argument 'profile_name'``

# Expectation / Proposal
Using credentials stored in a prefect blocks works. Even better, I can use a prefect s3 block directly.

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!
