### ISSUE TITLE
First class handling of dependencies from pyproject.toml after git_clone pull step

### ISSUE THREAD

**Issue by maitlandmarshall** [PrefectHQ/prefect#13252]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Prefect can use a pull step to install via requirements.txt or executing a script pull step.

### Describe the proposed behavior

Allow Prefect to install dependencies via a pyproject.toml file or remove the requirement to have a pull step, so that the project can be installed via EXTRA_PIP_PACKAGES and the entrypoint can be a module referencing to the installed pip package.

Here is a workaround I use for this, where I have a git clone pull step as well as an EXTRA_PIP_PACKAGES step referencing the same package so I can install the dependencies:

  ```yaml
- name: devprod-all
    tags: [service:upp_viewpoint, env:devprod]
    entrypoint: customer_data_upp.dw.ingest:ingest_all_suppliers_and_answers
    work_pool:
      name: default
      job_variables:
        name: upp-devprod-all
        image: imageloc.azurecr.io/mad.docker.prefect_k8_job:816
        env:
          GIT_ACCESS_TOKEN: "{{ prefect.blocks.secret.pat-devops-customer }}"
          UPP_API_CREDENTIALS_BLOCK: prod
          CUSTOMER_DATA_UPP_BLOCK: dev-prodtest
          EXTRA_PIP_PACKAGES: git+https://path/to/repo@dev
    schedules:
      - cron: 0 0 * * *
        timezone: UTC
        day_or: true
    pull:
      - prefect.deployments.steps.git_clone:
          repository: https://path/to/repo@dev
          branch: dev
          access_token: "{{ prefect.blocks.secret.pat-devops-customer}}"
```
