### ISSUE TITLE
Prefect Cloud: A comma in a Deployment Title crashes every run in the Deployment - without any error messages as to why

### ISSUE THREAD

**Issue by grochmal** [PrefectHQ/prefect#13705]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The flow in the code block below is trivial.  It runs fine.  When i build a `prefect.yaml` in this form i can run the flow without issues:

`prefect.yaml`

```
name: mammoth
prefect-version: 2.16.8
build:
push:
pull:
deployments:
- name: Bored mammoth Will chase humans later
  version:
  tags: []
  description:
  entrypoint: ./pipelines/simple_flow.py:bored_mammoth
  parameters: {}
  work_pool:
    name: small-ecs-push-pool
    work_queue_name:
    job_variables: {}
  schedules: []
```

Out:
<img width="1196" alt="Screenshot 2024-05-31 at 10 54 31" src="https://github.com/PrefectHQ/prefect/assets/3606393/61e85898-35fb-4e22-ba3c-196466636b99">

But with this `prefect.yaml` the flow crashes

```
name: mammoth
prefect-version: 2.16.8
build:
push:
pull:
deployments:
- name: Bored mammoth, Will chase humans later
  version:
  tags: []
  description:
  entrypoint: ./pipelines/simple_flow.py:bored_mammoth
  parameters: {}
  work_pool:
    name: small-ecs-push-pool
    work_queue_name:
    job_variables: {}
  schedules: []
```

Out:
<img width="1208" alt="Screenshot 2024-05-31 at 11 00 43" src="https://github.com/PrefectHQ/prefect/assets/3606393/789d6333-a2bb-441a-b6de-c657833c6465">

The only difference it the comma in the name of the flow "Bored mammoth, Will chase humans later".

The comma makes the line into an array in the YAML.  But i did try quoting the name to force it into a string and it resulted in the same crash.  Namely this `prefect.yaml` also crashes:

```
name: mammoth
prefect-version: 2.16.8
build:
push:
pull:
deployments:
- name: "Bored mammoth, Will chase humans later"
  version:
  tags: []
  description:
  entrypoint: ./pipelines/simple_flow.py:bored_mammoth
  parameters: {}
  work_pool:
    name: small-ecs-push-pool
    work_queue_name:
    job_variables: {}
  schedules: []
```

I have bisected the source of this crash (that is it the comma in here) pretty much to death.  Prefect Cloud does not provide any error message as to why the crash happens.  The work pool used is an `ecs:push` pool, and the run crashes before AWS sees anything from prefect cloud about the run.  The run crashes before it is deployed into the work pool.

I did try starting a local instance of prefect, and the same code and `prefect.yaml` seem to just work.  Yet i may have massively misconfigured my local prefect instance since i did hack the SQLite background a good deal to make it work locally.  I am not confident in my (failed) attempts to reproduce this on a local deployment.  The cloud deployment though, reproduces everytime.

### Reproduction

```python3
from pydantic import BaseModel
from prefect import flow


class LargeMammalConfig(BaseModel):
    activity: str = "Chase Humans"
    location: str = "/tmp/mammoth.txt"


@flow(name="Bored mammoth: Will chase humans later")
def bored_mammoth(config: LargeMammalConfig) -> None:
    with open(config.location, "w") as f:
        f.write(f"I'm bored, i want to {config.activity}\n")
```

### Versions

```Text
Version:             2.16.8
API version:         0.8.4
Python version:      3.11.9
Git commit:          11cb641c
Built:               Fri, Mar 29, 2024 11:01 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```
