### ISSUE TITLE
Env vars set from a Prefect secret in prefect.yaml are showing up under the deployment configuration in the UI

### ISSUE THREAD

**Issue by tomasmv** [PrefectHQ/prefect#14088]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm setting an environment variable in my prefect.yaml via a series of definitions:

```
definitions:
  work_pools:
    work_pool: &work_pool
      name: my-ecs-pool
      work_queue_name:
      job_variables: &work_pool_job_variables
        env: &work_pool_env_variables
          REDSHIFT_PW: "{{ prefect.blocks.secret.password }}"
```
When I deploy my flow and check under the `Configuration` tab for the deployment, I see the raw value of my secret.

### Reproduction

```python3
definitions:
  work_pools:
    work_pool: &work_pool
      name: my-ecs-pool
      work_queue_name:
      job_variables: &work_pool_job_variables
        env: &work_pool_env_variables
          REDSHIFT_PW: "{{ prefect.blocks.secret.password }}"

deployments:
  - name: test
    version:
    tags:
      - test
    description:
    entrypoint: flows/flow_elt.py:elt_flow
    work_pool: *work_pool_stg
```

### Versions

```Text
2.16.8
```
