### ISSUE TITLE
`prefect deploy` fails with a trigger using the `within` field

### ISSUE THREAD

**Issue by collincchoy** [PrefectHQ/prefect#14309]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a `prefect.yaml` containing a deployment definition with a trigger on it that successfully deploys with 2.x but fails using 3.x in the following way:

<img width="742" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/0a849a4f-36bb-4d75-b1e9-b1a4f1b6d040">

### Reproduction
attempt to `prefect deploy my_flows/some_params.py:some_params` using a `prefect.yaml` deployments block like the below:

```yaml
...
deployments:
- name: deploy-some-params
  version:
  tags: []
  description:
  entrypoint: my_flows/some_params.py:some_params
  triggers:
  - type: event
    enabled: true
    match:
      prefect.resource.id: collin
    expect:
    - collins-event
    posture: Reactive
    threshold: 5
    within: 60  # fails because of this
    name: deploy-some-params__automation_1
  schedules: []
  pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /Users/collin/code/prefect
  enforce_parameter_schema: true
  work_pool:
    name: turtles
    work_queue_name:
    job_variables: {}
```

### Error

```python3
> Unexpected template type 'timedelta'
```

### Versions (`prefect version` output)

```Text
main
```
