### ISSUE TITLE
Add k8s livenessProbe

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1452]
## Use Case
It would be nice for a k8s agent to have a liveness probe for container kicking in case of hanging threads.

## Solution
Have the main agent process either write something to a file or a global object. Then the liveness probe can check the last time it was written and kick the container if it's stale.

```
    livenessProbe:
      exec:
        command:
        - check_liveness_object_or_something
      initialDelaySeconds: 5
      periodSeconds: 5
```

## Alternatives
We could have the liveness probe actually look at the PID of the main agent process but that may be difficult to predict.
