### ISSUE TITLE
`agent install` w/ `--resource-manager` fails on imagePullSecrets map

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1468]
## Description
`map: map[] does not contain declared merge key: name` when running `prefect agent install --resource-manager | kubectl apply --namespace=bleh -f -`

## Expected Behavior
It should have applied fine because without `--resource-manager` it works well

## Reproduction
If you remove
```
      imagePullSecrets:
      - {name: ''}
```
from the YAML it works. 

Solution: will keep out the imagePullSecrets block

## Environment
N/A

**Comment by bnaul** [comment]
FYI I still see this behavior running on master after #1469 :
```
(model) ➜  model git:(prefect) ✗ prefect agent install kubernetes -t TOKEN --resource-manager
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: prefect-agent}
  name: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels: {app: prefect-agent}
  template:
    metadata:
      labels: {app: prefect-agent}
    spec:
      containers:
      - args: [prefect agent start kubernetes]
        command: [/bin/bash, -c]
        env:
        - {name: PREFECT__CLOUD__AGENT__AUTH_TOKEN, value: TOKEN}
        - {name: PREFECT__CLOUD__API, value: 'https://api.prefect.io'}
        - {name: NAMESPACE, value: default}
        - {name: IMAGE_PULL_SECRETS, value: ''}
        image: prefecthq/prefect:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: [python, -c, from prefect.agent.kubernetes.agent import check_heartbeat;
                check_heartbeat()]
          failureThreshold: 2
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent
        resources:
          limits: {cpu: 100m, memory: 128Mi}
      - args: [python -c 'from prefect.agent.kubernetes import ResourceManager; ResourceManager().start()']
        command: [/bin/bash, -c]
        env:
        - {name: PREFECT__CLOUD__AGENT__AUTH_TOKEN, value: TOKEN}
        - {name: PREFECT__CLOUD__API, value: 'https://api.prefect.io'}
        - {name: PREFECT__CLOUD__AGENT__RESOURCE_MANAGER__LOOP_INTERVAL, value: '60'}
        - {name: NAMESPACE, value: default}
        image: prefecthq/prefect:latest
        imagePullPolicy: Always
        name: resource-manager
        resources:
          limits: {cpu: 100m, memory: 128Mi}
      imagePullSecrets:
      - {name: ''}
```
removing the last block still fixes the issue
