### ISSUE TITLE
PREFECT_API_URL not recognized even though it is set

### ISSUE THREAD

**Issue by ricardogsilva** [PrefectHQ/prefect#14906]
### Bug summary

I'm running prefect from the official docker image in a compose stack. Trying to launch a server, I use the following:

```yaml
  prefect-server:
    image: "prefecthq/prefect:3.0.0rc16-python3.10"
    command: ["prefect", "server", "start"]
    environment:
      PREFECT_PROFILES_PATH: "/prefect_profiles.toml"
      PREFECT_PROFILE: "my-profile"
      PREFECT_API_URL: "http://0.0.0.0:4200/api"
      PREFECT_CLI_PROMPT: false
      PREFECT_DEBUG_MODE: true
      PREFECT_HOME: "/prefect_home"
      PREFECT_SERVER_ALLOW_EPHEMERAL_MODE: false
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_SERVER_API_PORT: "4200"
      PREFECT_SERVER_CSRF_PROTECTION_ENABLED: true
      PREFECT_UI_API_URL: "http://localhost:8877/prefect/api"
      PREFECT_UI_URL: "http://localhost:8877/prefect"
      PREFECT_UI_SERVE_BASE: "/prefect"
```

As can be seen, I am setting `PREFECT_API_URL` via environment. When I stand up my stack and go check the prefect server logs, I get this:

```
15:21:53.432 | DEBUG   | prefect.profiles - Using profile 'my-profile'
`PREFECT_API_URL` is not set. You need to set it to communicate with the server.
? How would you like to proceed? [Use arrows to move; enter to select] 
> Create a new profile with `PREFECT_API_URL` set and switch to it     
  Set `PREFECT_API_URL` in the current profile: 'arpav-ppcv-server-dev'
 ___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _| 
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| |___\___| |_|  

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api

View the API reference documentation at http://0.0.0.0:4200/docs

Check out the dashboard at http://0.0.0.0:4200
```

As seen by the above output, the prefect server container is telling me that it does not recognize that I have set the `PREFECT_API_URL` variable via environment. It is also showing me what seems like an interactive prompt, which I unfortunately cannot use, and which I though I had disabled when I set the `PREFECT_CLI_PROMPT=false` environment variable - for this reason I'm not sure what the outcome is, as the logs do not reveal what was selected.

Nevertheless, and since I set `PREFECT_SERVER_API_HOST=0.0.0.0` and `PREFECT_SERVER_API_PORT=4200` I would expect the server to be up and running - which seems to be confirmed by the log output. So, looking at these logs I thought I would be able to access the prefect API at `http://127.0.0.1:4200/api` from inside the running container and that I would be able to access it also from any other container in the stack at `http://prefect-server:4200/api`. Turns out I cannot, as shown by this snippet:

```shell
docker exec -ti my-stack-prefect-server-1 python -c 'import requests; response = requests.get("http://127.0.0.1:4200/api"); print(response.status_code)'

404
```

As you can see by the output being `404` (not found), it seems the prefect server is not running at the address I expect - so I'm wondering where is it running then? I'm also thinking that the output of the logs seems very misleading, as it told me to visit this address. 

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc16
API version:         0.8.4
Python version:      3.10.14
Git commit:          aad66936
Built:               Mon, Aug 12, 2024 3:51 PM
OS/Arch:             linux/x86_64
Profile:             arpav-ppcv-server-dev
Server type:         server
Pydantic version:    2.8.2
```
```


### Additional context

_No response_
