### ISSUE TITLE
TOML Poetry support

### ISSUE THREAD

**Issue by LarsParTec** [PrefectHQ/prefect#15043]
### Describe the current behavior

Prefect configuration parameters are defined in `profiles.toml`.

### Describe the proposed behavior

Allow Prefect configuration parameters to be defined in Poetry's `pyproject.toml`.

### Example Use

```
[tool.flake8]
max-line-length = 88

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true

[tool.prefect]
PREFECT_API_KEY = "pnu_xyz"
PREFECT_API_URL = "http://127.0.0.1:4200/api"
PREFECT_LOGGING_SETTINGS_PATH = "~/myproject/.prefect/logging.yml"
```

### Additional context

[Poetry](https://python-poetry.org) is a popular dependency manager configured in `pyproject.toml`. Many third party tools can be configured in subsections of  `pyproject.toml` which prevents each tool requiring its individual `toml` file. See *Flake8* and *MyPy* in the above example.

It would be extremely helpful, if Prefect could retrieve its settings from `pyproject.toml` if such a file exists.

**Comment by cicdw** [comment]
Yea @desertaxle and I have been brainstorming on some improvements to how we manage Prefect settings and this falls nicely into that. Definitely game to consider this.

**Comment by desertaxle** [comment]
Hey @LarsParTec! I see you also submitted https://github.com/PrefectHQ/prefect/issues/15044, which looks like it's also related to settings. Would you see these two proposals as complementary, or is there one approach that you'd prefer?

**Comment by LarsParTec** [comment]
@desertaxle All Prefect configs (including logging) in a subsection of `pyproject.toml` would be our preferred solution.

But not all projects are working with the Poetry framework though. #15044 is an additional feature request and might be the lower hanging fruit.

**Comment by LarsParTec** [comment]
Related is [my question in your Slack channel](https://prefect-community.slack.com/archives/C048ZHT5U3U/p1724313056107139).
Do you really need a `yaml` and a `toml`? Or would a single `.prefect/profile.toml` suffice?

**Comment by LarsParTec** [comment]
Lastly, how can I define paths relative to our git repo (project directory) in the `logging.yml` below?
```
    file:
        level: 0
        class: logging.handlers.RotatingFileHandler
        filename: /Users/lars/Code/myproject/myproject.log
        # filename: myproject.log
        maxBytes: 10485760
        backupCount: 5
        formatter: standard
```
I do not want to write the logs to `PREFECT_HOME` but a directory one up from `PREFECT_HOME` i.e. the project home directory.

**Comment by OliverKleinBST** [comment]
Please note that the use/support of pyproject.toml is not bound to poetry, as pyproject.toml is adopted outside of poetry these days. https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

**Comment by LarsParTec** [comment]
@OliverKleinBST Great! Thanks a lot. I did not know.

Then I would suggest to focus on replacing `profile.toml` and `logging.yaml` by `pyproject.toml`. And I close https://github.com/PrefectHQ/prefect/issues/15044

**Comment by LarsParTec** [comment]
One further advantage of `pyproject.toml`. Relative paths defined in `pyproject.toml` are relative to the location of the `pyproject.toml` file.

```
my_tool/
├── pyproject.toml
├── my_tool.log
├── src/
│   └── main.py
└── tests/
    └── test_main.py
```
For example, in the above project I can define the position in the log file. 
```
[tool.my_tool]
source_dir = "src"
test_dir = "tests"
log_file = my_tool.log
```
On the other hand, in Prefect's `logging.yaml` I can define only absolute paths or paths relative to the **current working directory**. Meaning the log file depends on where the user starts the Prefect workflow.
```
    file:
        level: 0
        class: logging.handlers.RotatingFileHandler
        # filename: /Users/lars/Code/my_tool/my_tool.log
        filename: my_tool.log
```
