### ISSUE TITLE
Deployment tags generated from step outputs do not populate in prefect.yaml

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#15096]
### Bug summary

The `tags` on a `deployments` item in `prefect.yaml` doesn't resolve step outputs (e.g. `{{ get-branch-name.stdout }}`). It does resolve environment variables (e.g. `{{ $FOO }}`) and step outputs are resolved in other places (e.g. in `version`). See the example `prefect.yaml` below. In this case I am using a branch named `my-branch`.

```yaml
name: example
prefect-version: 2.20.3

build:
- prefect.deployments.steps.run_shell_script:
    id: get-branch-name
    script: git branch --show-current
    stream_output: true
- prefect.deployments.steps.run_shell_script:
    id: confirm-branch-name
    script: echo '{{ get-branch-name.stdout }}'
    stream_output: true

push: null
pull: null

deployments:
- name: default
  version: "{{ get-branch-name.stdout }}"
  description: null
  entrypoint: flows/hello.py:hello
  parameters: {}
  tags:
    - this-appears
    - "{{ $FOO }}"
    - "{{ get-branch-name.stdout }}"
  work_pool:
    name: process
    work_queue_name: null
    job_variables: {}
  enforce_parameter_schema: true
```

Running `prefect deploy` and inspecting the deployment, you can see that the branch is not included as a tag:

```bash
$ FOO=bar prefect --no-prompt deploy -n 'hello/default'
...

$ prefect deployment inspect 'hello/default' | grep version
    'version': 'my-branch',

$ prefect deployment inspect 'hello/default' | grep tags
    'tags': ['this-appears', 'bar'],

### Version info (`prefect version` output)

```Text
Version:             2.20.3
API version:         0.8.4
Python version:      3.12.5
Git commit:          b8c27aa0
Built:               Thu, Aug 22, 2024 3:13 PM
OS/Arch:             darwin/arm64
Profile:             sandbox
Server type:         cloud
```
