### ISSUE TITLE
Prefect-docker `push_docker_image` unwanted cache hit

### ISSUE THREAD

**Issue by mch-sb** [PrefectHQ/prefect#15258]
### Bug summary

Hey!
Im wondering if the caching [here](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-docker/prefect_docker/deployments/steps.py#L261) is a little aggressive, and is resulting in a cachehit when it should not, or im using this the wrong way?
Case:
I have a `prefect.yaml` with something like this:

```
definitions:
  docker_build: &docker_build
    - prefect.deployments.steps.run_shell_script:
        id: get-commit-hash
        script: git rev-parse --short HEAD
        stream_output: false
    - prefect_docker.deployments.steps.build_docker_image:
        id: build-image
        requires: prefect-docker==0.6.0
        image_name: "{{ prefect.variables.dp_test_project_image_name }}"
        tag: latest
        additional_tags:
          - "{{ get-commit-hash.stdout }}"
  docker_push: &docker_push
    - prefect_docker.deployments.steps.push_docker_image:
        requires: prefect-docker==0.6.0
        image_name: "{{ build-image.image_name }}"
        tag: "{{ build-image.tag }}"
        additional_tags: "{{ build-image.additional_tags }}"

...
build: *docker_build
pull: *docker_pull
push: *docker_push
...

deployments:
  ... 
  - name: "dp-test-project-example-hello-world"
    version:
    description:
    entrypoint: flows/examples/hello_world.py:hello_world
    tags:
      - "dp-test-project"
      - "example-deployment"
    work_pool:
      <<: *work_pool
      job_variables:
        <<: *calculator
    ...
```

And running with:
```
poetry run prefect \
            --no-prompt deploy \
            --name dp-test-project-example-hello-world
```

From what i can see `build_docker_image`  results in cache key creation, `push_docker_image` hits that cachekey, as the cachekey does not contain the function used, and we are not doing a `push_docker_image` ?
ref. https://docs.prefect.io/3.0/deploy/infrastructure-concepts/prefect-yaml#define-deployments-with-yaml
Workaround is using the `ignore_cache`  for the `prefect_docker.deployments.steps.push_docker_image` -step, but i guess it could be ok to have cache sometimes. But as there is state outside of the `push_docker_image` which can affect it (a new image created with the same tag for instance), i would guess the image hash or something should also be in there (the cache-key)?
If you could point me towards how not to hit the cache, or an alternative way, that would be great

### Version info (`prefect version` output)

```Text
prefect --version
3.0.0

prefect-docker==0.6.0
```

### Additional context

The docs seems a little outdated, ref. https://docs.prefect.io/3.0/deploy/infrastructure-concepts/prefect-yaml#define-deployments-with-yaml ?

I see:
```
            - prefect_docker.deployments.steps.build_docker_image: &docker_build_config
                id: build-image
                requires: prefect-docker>=0.3.0
                image_name: my-example-image
                tag: dev
                dockerfile: auto
                push: true
```

I vaguely remember the `push` flag as an old deprecated flag (now removed)? Or should I use the `push`-flag instead of the `push_docker_image `-step?

**Comment by mch-sb** [comment]
Another workaround:

```
    - prefect_docker.deployments.steps.build_docker_image:
        id: build-image
        requires: prefect-docker==0.6.0
        image_name: "{{ prefect.variables.dp_test_project_image_name }}"
        tag: latest
        dockerfile: Dockerfile # added
        additional_tags:
          - "{{ get-commit-hash.stdout }}"
  docker_push: &docker_push
    - prefect_docker.deployments.steps.push_docker_image:
        requires: prefect-docker==0.6.0
        image_name: "{{ build-image.image_name }}"
        tag: "{{ build-image.tag }}"
        additional_tags: "{{ build-image.additional_tags }}"
```

With this the params to `push_docker_image` and `build_docker_image` are not the same, and they are not hiting eachothers cache it seems
