### ISSUE TITLE
Deploy all to enable sync of yaml and server deployments

### ISSUE THREAD

**Issue by frantakalab** [PrefectHQ/prefect#15332]
### Describe the current behavior

Assume I have two deployments in my `prefect.yaml`:
```
name: importers

deployments:
- name: deployment-1
  entrypoint: one.py:flow

- name: deployment-2
  entrypoint: two.py:flow
```

I run `prefect --no-prompt deploy --all --prefect-file prefect.yaml` and two of these deployments get created on the server.

Next I delete `deployment-2` in my yaml. I run the same deploy command, on the server `deployment-1` is updated and `deployment-2` is kept.

### Describe the proposed behavior

The command should synchronize the definitions in the yaml with the server (check for deletion as well). If someone is needing this "non-deletion" behavior, then adding a flag like `--sync, or --sync-all` would seem like a good descriptive name.

Important is to keep this per `name`, to make sure this does not delete deployments defined and created from other places.

### Example Use

for automated deployments, where deployment definitions are as a code I would expect synchronisation to be the default.
