### ISSUE TITLE
Deploy with missing dependencies breaks when flow decorator uses an imported variable

### ISSUE THREAD

**Issue by borovikova** [PrefectHQ/prefect#15352]
### Bug summary

Hello,

We use variables when defining the name in the flow decorator. I noticed that it breaks the deploy when some dependencies are missing, causing `ModuleNotFoundError`. When a plain string is used, deploy works fine.

Here is my test flow:

```python
import pandas as pd # pandas is not installed
from prefect import flow, task

from constants import FLOW_NAME

@task
def create_and_print_dataframe():
    df = pd.DataFrame({
        'A': [1, 2, 3],
        'B': [4, 5, 6]
    })
    print(df)

@flow(name=FLOW_NAME) # this causes an error during deployment
# @flow(name='test') # this works
def pandas_flow():
    create_and_print_dataframe()
```

`constants.py`:
```python
FLOW_NAME='test'
```

`prefect.yaml`:

```yaml
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /your_directory/prefect-example

deployments:
- name: default
  version: null
  tags: []
  description: null
  entrypoint: my_workflow.py:pandas_flow
  parameters: {}
  work_pool:
    name: my-work-pool
    work_queue_name: null
    job_variables: {}
  schedules: []
```

The deployment command:
```bash
prefect --no-prompt deploy --all --prefect-file prefect.yaml
```

I put everything in a repo [here](https://github.com/borovikova/prefect-example/tree/main) for convenience.

### Version info (`prefect version` output)

```Text
Version:             3.0.0
API version:         0.8.4
Python version:      3.10.12
Git commit:          c40d069d
Built:               Tue, Sep 3, 2024 11:13 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Pydantic version:    2.9.1
```
