### ISSUE TITLE
Lazy templating for deployments in prefect.yaml

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#15489]
### Describe the current behavior

Currently when using prefect file for deploying deployments to Prefect Server, all template variables (`{{ }}`) are evaluated at deploy time. This behavior does not allow evaluating `prefect.block` or `prefect.variable` at deployment runtime and thus, any changes to the data in the references does not take effect after deployment.
Any other variables like `{{ event.resource... }}` passed to deployment trigger parameters also does not work.

### Describe the proposed behavior

**First solution** could be to  implement some logic to allow lazy evaluation/parsing of template variables, that under some conditions would be either evaluated later in the deploy process or at deployment runtime. This logic could prove to be tricky and not intuitive for the users.  
**Probably better solution** might be to implement an option to explicitly mark templating variable to be evaluated at deploy, or at deployment runtime (in `Flow.validate_parameters` forexample). 

For blocks, it would require to update block evaluation to pass only reference dict object instead of resolved data object.

If there is a will to approve this enhancement, i volunteer to work on it as this is something that would really help me move from deployment definition in python. If there is a need for better design definition for the acceptance, let me know.

### Example Use

```
deployments:
- name: MyDeployment
  description: null
  entrypoint: "my_module:my_flow"
  parameters:
    blocks: 
      - "{{ prefect.blocks.my-block-type.my-block1:runtime }}"  # example
      - "{{ prefect.blocks.my-block-type.my-block1|runtime }}"  # example
      - "{{ lazy:prefect.blocks.my-block-type.my-block1 }}"  # example
      - "{{ lazy|prefect.blocks.my-block-type.my-block1 }}"  # example
      - "{{ ref|prefect.blocks.my-block-type.my-block1 }}"  # example
      - "{{ ref:prefect.blocks.my-block-type.my-block1 }}"  # example
```
