### ISSUE TITLE
Can't get `prefect cloud login` to work

### ISSUE THREAD

**Issue by trymzet** [PrefectHQ/prefect#15566]
### Bug summary

While testing a GitHub workflow locally with `act`, I can't get the `prefect cloud login` command to work, despite the fact that all of the required params are correct. Unfortunately, there is no error message from the CLI - I only get a generic `httpx.ConnectTimeout` error from the underlying networking lib, so it's hard to figure out what the issue is.

It seems the command is performing some internal logic with the `profiles.yml` file in the background - maybe it fails because it doesn't work as the tool expects?

I would expect the command to work if the params are correct, regardless of what is happening with the `profiles.yml` file (I don't need that file anyway).

### Version info (`prefect version` output)

```Text
| Version:             2.20.9
| API version:         0.8.4
| Python version:      3.10.14
| Git commit:          b101915a
| Built:               Tue, Oct 1, 2024 12:41 PM
| OS/Arch:             linux/x86_64
| Profile:             default
| Server type:         ephemeral
| Server:
|   Database:          sqlite
|   SQLite version:    3.37.2
```

### Additional context

```python
Traceback (most recent call last):
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
|     return fn(*args, **kwargs)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 311, in coroutine_wrapper
|     return call()
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
|     return self.result()
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
|     return self.future.result(timeout=timeout)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
|     return self.__get_result()
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
|     raise self._exception
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
|     result = await coro
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/cli/cloud/__init__.py", line 455, in login
|     workspaces = await client.read_workspaces()
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/client/cloud.py", line 91, in read_workspaces
|     List[Workspace], await self.get("/me/workspaces")
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/client/cloud.py", line 119, in get
|     return await self.request("GET", route, **kwargs)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/client/cloud.py", line 123, in request
|     res = await self._client.request(method, route, **kwargs)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_client.py", line 1585, in request
|     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/client/base.py", line 327, in send
|     response = await self._send_with_retry(
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect/client/base.py", line 251, in _send_with_retry
|     response = await send(request, *send_args, **send_kwargs)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
|     response = await self._send_handling_auth(
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
|     response = await self._send_handling_redirects(
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
|     response = await self._send_single_request(request)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
|     response = await transport.handle_async_request(request)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
|     with map_httpcore_exceptions():
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/contextlib.py", line 153, in __exit__
|     self.gen.throw(typ, value, traceback)
|   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
|     raise mapped_exc(message) from exc
| httpx.ConnectTimeout
```

**Comment by zzstoatzz** [comment]
hi @trymzet - generally speaking, you should only have to set `PREFECT_API_KEY` and `PREFECT_API_URL` as `env` in your Github Action.

I think we should update the `actions-prefect-auth` accordingly - can you try just setting the env vars?

**Comment by trymzet** [comment]
Hi @zzstoatzz, I tried several ways and couldn't get it to work:

1. The official Prefect action

```yaml
- name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ vars.PREFECT_WORKSPACE }}
```

(error: timeout)

2. The official action + env vars

```yaml
- name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        env:
          PREFECT_API_URL: ${{ vars.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ vars.PREFECT_WORKSPACE }}
```

(error: timeout)

3. CLI with options

```yaml
- name: Authenticate with Prefect
        run: prefect cloud login --workspace ${{ vars.PREFECT_WORKSPACE }} --key ${{ secrets.PREFECT_API_KEY }}
```

(error: this is asking me for some input, so can't execute this programmatically)

4. CLI with options + `--no-prompt` option

```yaml
- name: Authenticate with Prefect
        run: prefect --no-prompt cloud login --workspace ${{ vars.PREFECT_WORKSPACE }} --key ${{ secrets.PREFECT_API_KEY }}
```

(error: When not using an interactive terminal, you must supply a `--key` and 
| `--workspace`.)

5. CLI with env vars

```yaml
- name: Authenticate with Prefect
        env:
          PREFECT_API_URL: ${{ vars.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: prefect cloud login
```

(error: this is asking me for some input, so can't execute this programmatically)

5. CLI with env vars + `--no-prompt` option

```yaml
- name: Authenticate with Prefect
        env:
          PREFECT_API_URL: ${{ vars.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: prefect --no-prompt cloud login
```

(error: When not using an interactive terminal, you must supply a `--key` and 
| `--workspace`.)
