### ISSUE TITLE
Deployment Fails Due to Missing Dependencies When Flow Decorator Imports Variable from a File Containing Missing Package

### ISSUE THREAD

**Issue by borovikova** [PrefectHQ/prefect#15764]
### Bug summary

Deploy with missing dependencies fails if the file from which we import a variable to use in the flow decorator contains an import of the missing package.

Test flow:
```
from prefect import flow

from constants import FLOW_NAME


@flow(name=FLOW_NAME)
def pandas_flow():
    ...
```

`constants.py`
```
import pandas as pd # pandas is not installed

FLOW_NAME='test'
```

`prefect.yaml`

```
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /your_directory/prefect-example

deployments:
- name: default
  version: null
  tags: []
  description: null
  entrypoint: my_workflow.py:pandas_flow
  parameters: {}
  work_pool:
    name: my-work-pool
    work_queue_name: null
    job_variables: {}
  schedules: []
  ```

I put everything in a repo [here](https://github.com/borovikova/prefect-example/tree/main) for convenience.

The issue was briefly discussed in https://github.com/PrefectHQ/prefect/issues/15352

### Version info (`prefect version` output)

```Text
Version:             3.0.0
API version:         0.8.4
Python version:      3.10.12
Git commit:          c40d069d
Built:               Tue, Sep 3, 2024 11:13 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Pydantic version:    2.8.2
```
