### ISSUE TITLE
`PREFECT_LOGGING_SERVER_LEVEL` not respected by FastAPI in `prefect server start`

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#15775]
### Bug summary

# FastAPI server logs not visible despite `PREFECT_LOGGING_SERVER_LEVEL` setting

## Current Behavior
- FastAPI and Uvicorn logs (e.g. request logs like `GET /bad-request 404`) are not visible even when `PREFECT_LOGGING_SERVER_LEVEL` is set
- This appears to be caused by `setup_logging` in `create_app`
- Removing `setup_logging` from `create_app` allows the logs to appear

## Expected Behavior
Server logs should be visible when `PREFECT_LOGGING_SERVER_LEVEL` is set, as suggested by our `logging.yml` configuration:
```yaml
uvicorn:
    level: "${PREFECT_LOGGING_SERVER_LEVEL}"

fastapi:
    level: "${PREFECT_LOGGING_SERVER_LEVEL}"
```

## Steps to Reproduce
1. Set `PREFECT_LOGGING_SERVER_LEVEL=DEBUG`
2. Start server
3. Make requests to endpoints
4. Observe that FastAPI/Uvicorn logs are not visible

### Version info (`prefect version` output)

```Text
main
```
