### ISSUE TITLE
CLI pool arguments is ignored when using --all switch on deploy

### ISSUE THREAD

**Issue by uncycler** [PrefectHQ/prefect#15791]
### Bug summary

I'm trying to deploy all flows with a default work pool but the pool argument is ignored:

```
$> prefect --no-prompt deploy --all --pool mypool

A work pool is required to deploy this flow. Please specify a work pool name via the '--pool' flag or in your prefect.yaml 
file.
```

The same thing happened with `PREFECT_DEFAULT_WORK_POOL_NAME`. It works fine when specifying the flow name.

### Version info (`prefect version` output)

```Text
Version:             3.0.10
API version:         0.8.4
Python version:      3.12.7
Git commit:          3aa2d893
Built:               Tue, Oct 15, 2024 1:31 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-kubernetes: 0.5.1
```

**Comment by desertaxle** [comment]
Hey @uncycler! When you deployed with that command you should've seen the following message:
```
You have passed options to the deploy command, but you are creating or updating multiple deployments. These options will be ignored.
```
When deploying multiple deployments, the `deploy` command ignores CLI arguments and only uses the configuration declared in your `prefect.yaml` file. You can work around this error by adding a work pool name to your `prefect.yaml` file for each deployment.

I would expect the `PREFECT_DEFAULT_WORK_POOL_NAME` setting to be respected in this case. I can look into ensuring that setting is respected in cases where you're deploying multiple flows.

**Comment by fchareyr** [comment]
> Hey @uncycler! When you deployed with that command you should've seen the following message:
> 
> ```
> You have passed options to the deploy command, but you are creating or updating multiple deployments. These options will be ignored.
> ```
> 
> When deploying multiple deployments, the `deploy` command ignores CLI arguments and only uses the configuration declared in your `prefect.yaml` file. You can work around this error by adding a work pool name to your `prefect.yaml` file for each deployment.
> 
> I would expect the `PREFECT_DEFAULT_WORK_POOL_NAME` setting to be respected in this case. I can look into ensuring that setting is respected in cases where you're deploying multiple flows.

Same issue here. Setting the default work pool name via either `prefect.toml` or `PREFECT_DEFAULT_WORK_POOL_NAME` does not seem to work.

This ask for a work pool name:
```yaml
definitions:
  work_pool: &common_work_pool
    job_variables:
       
deployments:
- name: basic-k8s-deployment
  description: An example Prefect deployment
  entrypoint: poc/jobs/flow.py:call_api
  work_pool: *common_work_pool

- name: starter-mapping
  description: Another example Prefect deployment
  entrypoint: poc/jobs/starter/mapping.py:my_flow
  work_pool: *common_work_pool
```

This is fine:
```yaml
definitions:
  work_pool: &common_work_pool
  name: "kubernetes-workpool"
    job_variables:
       
deployments:
- name: basic-k8s-deployment
  description: An example Prefect deployment
  entrypoint: poc/jobs/flow.py:call_api
  work_pool: *common_work_pool

- name: starter-mapping
  description: Another example Prefect deployment
  entrypoint: poc/jobs/starter/mapping.py:my_flow
  work_pool: *common_work_pool
```
