### ISSUE TITLE
Deploy boolean arg `--enforce-parameter-schema` can't be set to False when multiple deployments specified in `--name`

### ISSUE THREAD

**Issue by gscholtes-relativity** [PrefectHQ/prefect#16438]
### Bug summary

`prefect-deploy` does not respect the value of `--enforce-parameter-schema` (or rather, specifically when it is set to false, `--no-enforce-parameter-schema`) if a wildcard is passed into `--name` and the wildcard matches more than 1 deployment.

Reproduction
---

Run each of these commands

```
$ prefect --no-prompt deploy --no-enforce-parameter-schema --name *-dog
$ prefect --no-prompt deploy --no-enforce-parameter-schema --name *-elephant
```

Using a `prefect.yaml` like this:

```yaml
- name: aardvark-dog
  version: v1.2.3
  entrypoint: *entrypoint
  work_pool:
    <<: *work_pool
    name: some-work-pool
    work_queue_name: Some Work Queue

- name: bandicoot-dog
  version: v1.2.3
  entrypoint: *entrypoint
  work_pool:
    <<: *work_pool
    name: some-work-pool
    work_queue_name: Some Work Queue

- name: cat-elephant
  version: v1.2.3
  entrypoint: *entrypoint
  work_pool:
    <<: *work_pool
    name: some-work-pool
    work_queue_name: Some Work Queue
```

**Expected behavior** - `enforce_parameter_schema` is `False` for each of `aardvark-dog`, `bandicoot-dog`, `cat-elephant`
**Actual behavior** - `enforce_parameter_schema` is `False` for `cat-elephant`, and `True` for `aardvark-dog`, `bandicoot-dog`

![image](https://github.com/user-attachments/assets/18485074-318e-4de6-955f-aaf52a71e177)

Fix
---

I believe this is the offending block:

https://github.com/PrefectHQ/prefect/blob/3.1.9.dev1/src/prefect/cli/deploy.py#L426-L447

It looks like this skip might be intentional? If so is there a purpose for that or a workaround? Regarding these lines:

```python
                        "You have passed options to the deploy command, but you are"
                        " creating or updating multiple deployments. These options"
                        " will be ignored."
```

### Version info

```Text
Version:             3.1.9.dev1
API version:         0.8.4
Python version:      3.10.12
Git commit:          068ea229
Built:               Tue, Dec 17, 2024 1:51 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
Pydantic version:    2.9.2
Integrations:
  prefect-azure:     0.4.2
```

**Comment by gscholtes-relativity** [comment]
I see that it is possible to set this in `prefect.yaml` instead, like this:

```yaml
- name: aardvark-dog
  version: v1.2.3
  entrypoint: *entrypoint
  enforce_parameter_schema: false
  work_pool:
    <<: *work_pool
    name: some-work-pool
    work_queue_name: Some Work Queue
```

But still I wonder if it is possible for the `prefect deploy` options to be respected in the same manner as when a single deployment is passed in (I imagine that the problem of choosing precedence of the CLI vs `prefect.yaml` would be the same in both cases, single vs multiple deployments).
