### ISSUE TITLE
Propagate Trigger descriptions from prefect yaml

### ISSUE THREAD

**Issue by masonmenges** [PrefectHQ/prefect#16655]
### Describe the current behavior

Current when defining a trigger via prefect yaml for a particular deployment the description for the trigger isn't passed to the created automation

For example This trigger definition creates an automation with the name "testing_trigger_description" but passing a description to the trigger still results in None being displayed for the automation triggers description
```
triggers:
    - type: event
      name: testing_trigger_description
      description: "some description"
      enabled: true
      match:
        prefect.resource.id: prefect.flow_run.*
      expect:
        - prefect.flow_run.Completed
```

Resulting Automation in the UI:

<img width="1283" alt="Screenshot 2025-01-08 at 3 41 00 PM" src="https://github.com/user-attachments/assets/d58d36f9-2c77-49df-a017-6df328c71748" />

### Describe the proposed behavior

Descriptions passed to a trigger definition via prefect yaml should be reflected in the description for the resulting automation trigger that gets created.
