### ISSUE TITLE
Prefect UI not working with Server API Auth (username:password)

### ISSUE THREAD

**Issue by shah1dk** [PrefectHQ/prefect#16724]
I'm trying to implement Authentication for Prefect Open Source while hosting the server locally.

My docker-compose for Prefect server looks like this:

```
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourTopSecretPassword
      - POSTGRES_DB=prefect
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  prefect:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:yourTopSecretPassword@db:5432/prefect
      - PREFECT_SERVER_API_AUTH_STRING="admin:admin"
    ports:
      - "4200:4200"
    depends_on:
      - db
```

This results in Prefect UI credential page, but as soon as page loads, I get a toast message in red saying `Authentication failed". It only asks for a password, and no matter what I put in the pwd field, it logins but shows the above toast message as well.

Please let me know if I'm doing anything wrong. Or if you've any documentation for above implementation.

Attaching screenshot here:
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/bc09718d-a466-43bd-b69a-e0775bd16e6c" />

Ref: https://github.com/PrefectHQ/prefect/issues/2238#issuecomment-2581153637_
