### ISSUE TITLE
Fix inconsistent deployment concurrency limit documentation

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#16800]
[This](https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml#concurrency-limit-fields) concurrency limit fields section of the docs suggests that the deployment YAML has the following structure:

```yaml
deployments:
  ...
  concurrency_limit:
    limit: <int>
    collision_strategy: <str>
```

When in fact it has the following structure:

```yaml
deployments:
  ...
  concurrency_limit: <int>
  concurrency_options:
    collision_strategy: <str>
```

This also slightly conflicts with the documentation [here](https://docs.prefect.io/v3/deploy/index#concurrency-limiting).
