### ISSUE TITLE
Error parsing boolean in DeploymentScheduleCreate

### ISSUE THREAD

**Issue by aurany** [PrefectHQ/prefect#16826]
### Bug summary

I get the following error when trying to have a parameterized value for the active field in schedule.

Error message
```
1 validation error for DeploymentScheduleCreate
active
  Input should be a valid boolean, unable to interpret input 
    For further information visit https://errors.pydantic.dev/2.10/v/bool_parsing
```

get-schedule-isactive.sh

```
#!/bin/sh
echo "false"
```

prefect.yaml
```
definitions:

  work_pools:
    docker_work_pool: &docker_work_pool
      name: docker-pool
      work_queue_name: "{{ get-work-pool.stdout }}"

  schedules:
    every_hour: &every_hour
      cron: "0 0 * * *"
      timezone: "America/Chicago"
      active: "{{ get-schedule-isactive.stdout }}"

  actions:

    docker_build: &docker_build
      - prefect.deployments.steps.run_shell_script:
          id: get-commit-hash
          script: git rev-parse --short HEAD
          stream_output: false
      - prefect.deployments.steps.run_shell_script:
          id: get-work-pool
          script: sh utils/get-work-pool.sh
          stream_output: false
      - prefect.deployments.steps.run_shell_script:
          id: get-schedule-isactive
          script: sh utils/get-schedule-isactive.sh
          stream_output: false
      - prefect_docker.deployments.steps.build_docker_image:
          id: build-image
          image_name: "repo/image"
          tag: "{{ get-commit-hash.stdout }}"
          dockerfile: Dockerfile

```

If I update the schedule in prefect-yaml like below it works fins.

```
schedules:
    every_hour: &every_hour
      cron: "0 0 * * *"
      timezone: "America/Chicago"
      active: "false"

```

Is this because of pydantic? Workarounds?

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.12.6
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.10.3
Integrations:
  prefect-docker:    0.6.2
  prefect-bitbucket: 0.3.1
```

### Additional context

_No response_kr
