### ISSUE TITLE
`prefect deploy` should validate yaml file before deploying

### ISSUE THREAD

**Issue by Ben-Epstein** [PrefectHQ/prefect#16996]
### Bug summary

I was working through this guide https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml#the-pull-action and was struggling to set the `set_working_directory` step because it's not actually specified how to use it. I tried

```
pull:
- prefect.deployments.steps.git_clone:
    id: clone-step
    repository: https://github.com/Team/repo
    branch: main
    credentials: '{{ prefect.blocks.github-credentials.my-repo-pull }}'
    set_working_directory: '{{ clone-step.directory }}/my-app'
```
as well as
```
- prefect.deployments.steps.git_clone:
    id: clone-step
    repository: https://github.com/Team/repo
    branch: main
    credentials: '{{ prefect.blocks.github-credentials.my-repo-pull }}'
- set_working_directory:  '{{ clone-step.directory }}/my-app'
```
(which is what prefect docs AI said, but didn't make sense to me)

as well as a few others, until I [searched for the usage of it in the repo](https://github.com/search?q=repo%3APrefectHQ%2Fprefect%20%22set_working_directory%22&type=code) to find the right syntax.

In each failed case, prefect was happy to let me deploy, but then failed when actually running the flow. This feels like it could be validated upfront to dramatically reduce my cycle time as a developer. 

### Version info

```Text
❯ uv run prefect version
Version:             3.1.15
API version:         0.8.4
Python version:      3.11.9
Git commit:          3ac3d548
Built:               Thu, Jan 30, 2025 11:31 AM
OS/Arch:             darwin/arm64
Profile:             ephemeral
Server type:         cloud
Pydantic version:    2.10.4
Integrations:
  prefect-github:    0.3.1
```
