### ISSUE TITLE
prefect deploy: `job_variables` not applied when using `--all` cli flag

### ISSUE THREAD

**Issue by andnig** [PrefectHQ/prefect#17110]
### Bug summary

When using the prefect cli deploy command with `--all` flag, it seems that job-variables provided with the deploy command are not applied.

The command I use is: ` prefect --no-prompt deploy --job-variable image=europe-docker.pkg.dev/vol-at/rm-datateam-repository/prefect-dbt-automation:dev-806 --all`

When running the prefect deploy command using `--name <deployment-name>` instead of `--all`, the job_variable (`image` in this case) is applied. However if  the `--all` flag is used, the job variable never gets applied - meaning the image which was set previously is used.
Note that I don't have the image specified in the `prefect.yml`.

The `prefect.yml`

```yaml
name: dbt_flows

build:

push:
  - prefect_gcp.deployments.steps.push_to_gcs:
      id: push_code
      bucket: <bucket>
      folder: prod/k8s/dbt_flows
      credentials: "{{ prefect.blocks.gcp-credentials.gcs-credentials }}"

pull:
  - prefect_gcp.deployments.steps.pull_from_gcs:
      id: pull_code
      bucket: "{{ push_code.bucket }}"
      folder: "{{ push_code.folder }}"
      credentials: "{{ prefect.blocks.gcp-credentials.gcs-credentials }}"

# the deployments section allows you to provide configuration for deploying flows
deployments:
  - name: run_dbt_pipeline_realtime_v2
    version:
    tags:
      - notify
      - prod_k8s
    description: Triggers a dbt run for realtime selector
    entrypoint: dbt_flows.py:run_dbt_pipeline
    work_pool:
      name: k8s
      work_queue_name: worker_prod_k8s_dbt_realtime
    concurrency_limit:
    enforce_parameter_schema: true
    schedules:
      - interval: 480
        timezone: Europe/Vienna
    build: null

  - name: run_dbt_pipeline_feast_daily_v2
    version:
    tags:
      - notify
      - prod_k8s
    description: Triggers a dbt run for api daily selector
    entrypoint: dbt_flows.py:run_dbt_pipeline
    work_pool:
      name: k8s
      work_queue_name: worker_prod_k8s_dbt_realtime
    concurrency_limit:
    enforce_parameter_schema: true
    schedules:
      - cron: 5 5 * * *
        timezone: Europe/Vienna
        day_or: true
    build: null
```

## Reproduction steps

As far as I can see this is reproducible with any flow:

1. Create an arbitrary flow
2. Use this flow for two or more deployments in `prefect.yml` (see exaple above)
3. Apply the `prefect.yml` with ` prefect --no-prompt deploy --job-variable image=europe-docker.pkg.dev/vol-at/rm-datateam-repository/prefect-dbt-automation:dev-806 --all`

### Result
The deployments get created, but the image is not part of the job variables or deployment configuration.

### Expected result
The job-variable is applied to all deployments, when using the `--all` flag

### Version info

```Text
Version:             3.2.1
API version:         0.8.4
Python version:      3.10.6
Git commit:          f8b15dfb
Built:               Mon, Feb 10, 2025 3:20 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
Pydantic version:    2.10.6
Integrations:
  prefect-gcp:       0.6.2
  prefect-shell:     0.3.1
  prefect-dbt:       0.6.5
```
