### ISSUE TITLE
prefect deploy is not updating the pull steps

### ISSUE THREAD

**Issue by LeeMendelowitz** [PrefectHQ/prefect#17182]
### Bug summary

Running `prefect --no-prompt  deploy --all` to deploy a `prefect.yaml` is failing to properly update the pull steps in Prefect Cloud for a `pull_from_s3` step if the `folder` changes. This is an issue with the latest version of prefect (3.2.4) and was not an issue under earlier versions (3.1.0).

Here's a reproducible example with a simple `prefect.yaml` file:

```
# Generic metadata about this project
name: Test Project

pull:
  - prefect_aws.deployments.steps.pull_from_s3:
      bucket: my-bucket
      folder: test_prefect_issue/v1

deployments:

  - name: test-prefect-issue
    entrypoint: flows/hello_world.py:hello_world
    work_pool:
      name: default-docker-pool
      work_queue_name: default
```

1. Call `prefect --no-prompt  deploy --all` to create the deployment for the first time. In the Prefect UI, I see it has the correct configuration:

```
[
  {
    "prefect_aws.deployments.steps.pull_from_s3": {
      "bucket": "my-bucket",
      "folder": "test_prefect_issue/v1"
    }
  }
]
```

2. Edit the `prefect.yaml` and change the folder to `test_prefect_issue/v2`.
3. Try to deploy with the updated configuration: `prefect --no-prompt  deploy --all`
4. In the Prefect UI, the configuration has not updated and still has the old folder:

```
[
  {
    "prefect_aws.deployments.steps.pull_from_s3": {
      "bucket": "my-bucket",
      "folder": "test_prefect_issue/v1"
    }
  }
]
```

This means that the flows that run in production will be using the wrong code.

### Version info

```Text
Version:             3.2.4
API version:         0.8.4
Python version:      3.12.4
Git commit:          701e7f48
Built:               Tue, Feb 18, 2025 9:31 PM
OS/Arch:             darwin/arm64
Profile:             test
Server type:         cloud
Pydantic version:    2.10.6
Integrations:
  prefect-aws:       0.5.3
  prefect-shell:     0.3.1
```
