### ISSUE TITLE
Allow path to environment file to be passed into prefect.yaml

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#17203]
### Describe the current behavior

With the deprecation of JSON blocks, users who have deployment specific configuration are advised to pass this configuration in using variables, which have a 5000 characters limit. For deployment specific configuration that is longer than that, they have to specify multiple variables, which is tedious. 

An example of this behavior would be when a Kubernetes config map/secrets configuration needs to get passed in on a per deployment basis: 
```json
[
  {
    "name": "SOME_CONFIGMAP_KEY",
    "valueFrom": {
      "configMapKeyRef": {
        "name": "some.configmap",
        "key": "key"
      }
    }
  },
  {
    "name": "VERY_IMPORTANT_SECRET_KEY",
    "valueFrom": {
      "SecretKeyRef": {
        "name": "very.important",
        "key": "secret_key"
      }
    }
  }
]
```

prefect.yaml with json block
```yaml
- name: test_deployment
  version:
  tags: []
  description:
  flow_name:
  entrypoint: src/main/test_flow.py:run
  work_pool:
    name: kubernetes-work-pool
    work_queue_name: general
    job_variables:
      image: fiverr/data_events_3.8_crons:latest
      job_watch_timeout_seconds: 3600
      pod_watch_timeout_seconds: 3600
      env: '{{ prefect.blocks.json.env-json }}'
```

### Describe the proposed behavior

Being able to reference environment file to the prefect.yaml, something like the below example 

### Example Use

```yaml
- name: test_deployment
  version:
  tags: []
  description:
  flow_name:
  entrypoint: src/main/test_flow.py:run
  work_pool:
    name: kubernetes-work-pool
    work_queue_name: general
    job_variables:
      image: fiverr/data_events_3.8_crons:latest
      job_watch_timeout_seconds: 3600
      pod_watch_timeout_seconds: 3600
      env: {% include env.yaml %}
```
