### ISSUE TITLE
Unexpected CLI prompt to save deployment configuration

### ISSUE THREAD

**Issue by ddeepwell** [PrefectHQ/prefect#17409]
### Bug summary

When creating a deployment via the CLI, a prompt to save the configuration occurs when an environment variable is set, but no prompt occurs when the variable is not set.

When no environment variable is set, prefect does throw a warning, but continues without prompting to save.

When the environment variable is set, prefect prompts to save and deploys the configuration as expected. I do not expect (nor want) the prompt since the file should be configured correctly.

Here is a minimum working example.

```yaml
#prefect.yaml
name: Env-var-bug
prefect-version:

build:
push:

pull:
  - prefect.deployments.steps.set_working_directory:
      directory: "{{ $WORKING_DIRECTORY }}"

deployments:
  - name: bugged-deployment
    version:
    tags: []
    concurrency_limit:
    description:
    entrypoint: flow.py:my_flow
    parameters:
      settings_file: "{{ $SETTINGS_FILE }}"
    work_pool:
      name: work-pool
      work_queue_name:
      job_variables: {}
    schedules: []
```

```python
#flow.py

from pathlib import Path
from prefect import flow


@flow(log_prints=True)
def my_flow(settings_file: Path):
    print(f"Running my scheduled flow with file {settings_file}...")
```

Case 1: Unset environment variable - does not prompt (as expected)

```bash
prefect deploy --name bugged-deployment
```

Case 2: Set environment variable - does prompt (unexpected)

```bash
export SETTINGS_FILE=prefect.yaml 
prefect deploy --name bugged-deployment
```

The prompt is: "Would you like to save configuration for this deployment for faster deployments in the future? [y/n]:"

Case 3: No environment variable - does not prompt (as expected)

Replace `"{{ $SETTINGS_FILE }}"` with `prefect.yaml` and execute:

```bash
prefect deploy --name bugged-deployment
```

### Version info

```Text
Version:             3.2.11
API version:         0.8.4
Python version:      3.13.2
Git commit:          9481694f
Built:               Wed, Mar 5, 2025 10:00 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
Pydantic version:    2.10.6
```
