### ISSUE TITLE
late flow runs get deleted on new prefect deploy

### ISSUE THREAD

**Issue by rcash** [PrefectHQ/prefect#17764]
### Bug summary

flow runs that are late or awaitingconcurrencyslot in a given deployment are deleted and not rescheduled when a fresh `prefect deploy` is issued for the deployment.

steps to reproduce:
1. deploy a simple flow like below to a process workpool
2. make sure schedule is active + flow runs are being kicked off
3. kill the process worker temporarily, let a few of the scheduled flow runs stack up as late
4. bring the process worker back up + run `prefect deploy`
5. all the late runs seem to have disappeared - and are replaced with the new deployment's runs, if applicable.

flow code:
```
import time
from prefect import flow, task


@task(log_prints=True)
def generic_task(name: str, sleep_time: int):
    print(f"Task {name} Started")
    print(f"sleeping for {sleep_time} seconds")
    time.sleep(sleep_time)
    print(f"Task {name} Completed")

@flow(log_prints=True)
def generic_flow():
    print("Starting Flow")
    a = generic_task.submit("a",25)
    print(a.result())
```

prefect.yaml contents:
```
deployments:
- name: default
  parameters: {}
  parameter_openapi_schema: {}
  entrypoint: simple_flow.py:generic_flow
  schedule:
    interval: 10 # seconds
    slug: "default-schedule"
    timezone: "America/New_York"
    active: true
```

### Version info

```Text
Version:             3.3.3
API version:         0.8.4
Python version:      3.12.9
Git commit:          4100d4ea
Built:               Sat, Apr 05, 2025 01:44 AM
OS/Arch:             darwin/arm64
Profile:             sbx-rowdy-cloud
Server type:         cloud
Pydantic version:    2.11.2
Integrations:
  prefect-databricks: 0.3.0
```

### Additional context

alternatively, set a `concurrency_limit` of 1 on the deployment and the task sleep to an amount of time greater than the interval on the schedule. let a few runs stack up, re-run `prefect deploy` and all the awaitingconcurrencyslot flow runs disappear.
