### ISSUE TITLE
Schedule Parameter Overrides do not apply on redeploy of Deployment

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#17846]
### Bug summary

When deploying a Prefect flow using the prefect.yaml, you can set default parameters for each schedule. 

When re-deploying a flow that has these defined, the scheduled runs that appear for the deployment schedule do not have the parameter override values for each scheduled flow run. 

Python flow file

```py
#flow.py with parameters

import dask.dataframe
import dask.distributed
from prefect import flow, task

@task
def read_data(start: str, end: str) -> dask.dataframe.DataFrame:
    df = dask.datasets.timeseries(start, end, partition_freq="4W")
    return df

@flow()
def dask_pipeline(list_of_dates = None):
    df = read_data.submit(list_of_dates["list_of_dates"][0], list_of_dates["list_of_dates"][1])
    print(df)

if __name__ == "__main__":
    dask_pipeline()
```

prefect.yaml with schedule defined: 
```yaml
# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: ecs-test-example
prefect-version: 3.3.4

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /Users/rob.freedy/Documents/prefect/scratch/ecs-test-example

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: test-schedule-param-override
  version: null
  tags: []
  concurrency_limit: null
  description: null
  entrypoint: flow.py:dask_pipeline
  parameters: 
    list_of_dates: {}
  work_pool:
    name: local-worker
    work_queue_name: null
    job_variables: {}
  schedules:
  - cron: '*/5 * * * *'
    timezone: UTC
    day_or: true
    active: true
    parameters:
      list_of_dates:
        list_of_dates:
          - 2030
          - 2040
```

Steps to reproduce: 

1. Copy the flow.py and prefect.yaml locally
2. Deploy flow.py using provided prefect.yaml and prefect deploy command
3. Change values in the schedule parameters section of the prefect.yaml
4. Re-deploy using prefect deploy command
5. Check in UI the scheduled flow runs parameters that are passed in 

<img width="535" alt="Image" src="https://github.com/user-attachments/assets/19cce8a5-1942-4cc8-9bae-6e6e4c569492" />

### Version info

```Text
Version:             3.3.4
API version:         0.8.4
Python version:      3.11.10
Git commit:          7ca03553
Built:               Fri, Apr 11, 2025 12:27 AM
OS/Arch:             darwin/arm64
Profile:             test
Server type:         cloud
Pydantic version:    2.10.2
Integrations:
  prefect-dask:      0.3.4
  prefect-azure:     0.4.2
  prefect-docker:    0.6.2
  prefect-gcp:       0.6.2
  prefect-github:    0.3.1
  prefect-snowflake: 0.28.2
  prefect-aws:       0.5.9
```
