### ISSUE TITLE
cloning private repo with submodule not working

### ISSUE THREAD

**Issue by benedictdebrah** [PrefectHQ/prefect#17884]
### Bug summary

please i am trying to clone a private repo that has a submodule inn it.
cloning private repo works but it fails when i add include_submodules = (True or true) to clone the submodules .

![Image](https://github.com/user-attachments/assets/7a01c5bb-4c09-471c-b1c8-3e12f2ee918e)

```
pull:
  - prefect.deployments.steps.git_clone:
      repository:url
      credentials: "{{ prefect.blocks.github-credentials.x }}"
      include_submodules: True (or true it still doesnt work)


```
the rest of the deployment continues

### Version info

```Text
Version:             3.3.5
API version:         0.8.4
Python version:      3.12.8
Git commit:          db4b7a33
Built:               Thu, Apr 17, 2025 09:25 PM
OS/Arch:             darwin/x86_64
Profile:             ephemeral
Server type:         cloud
Pydantic version:    2.11.3
Integrations:
  prefect-docker:    0.6.2
  prefect-github:    0.3.1
  prefect-shell:     0.3.1
```
