### ISSUE TITLE
Deployment yaml variable injection inline substitution

### ISSUE THREAD

**Issue by jlwhelan28** [PrefectHQ/prefect#17916]
### Describe the current behavior

Currently when working with the yaml definition of a deployment you can inject variables / block data, but the variable reference cannot be used for inline string substitution. In other words the variable reference contained by {{...}} must be the only thing present in the key value.

Example:
```
build:
- prefect_docker.deployments.steps.build_docker_image:
    id: build_image
    image_name: '{{ prefect.blocks.secret.my-private-image.value }}'
```

### Describe the proposed behavior

Handle inline substitution similar to how environment variables work in sh, or the cloudformation "!Sub" intrinsic function.

Example:
```
prefect.blocks.secret.my-private-repo.value -> resolves to my-private-repo.com
```
```
build:
- prefect_docker.deployments.steps.build_docker_image:
    id: build_image
    image_name: '{{ prefect.blocks.secret.my-private-repo.value }}/my-image-name'
```

Gets processed by prefect such that `image_name = my-private-repo.com/my-image-name`

### Additional context

Originally suggested in https://github.com/PrefectHQ/prefect/issues/17604#issuecomment-2755086368
