### ISSUE TITLE
Deploy a deployment without overriding values that were declared in the UI

### ISSUE THREAD

**Issue by ChrisPaul33** [PrefectHQ/prefect#18019]
### Describe the current behavior

When updating a deployment, the parameters and schedules declared in the `prefect.yaml` are all overriding the current values.
For most cases it's fine.
But I have a case when there is an operation team that make changes in the UI only!
Once in a while, I need to update the image of the deployment, but I don't want to override any (or most) of the UI parameters, schedules and more. 

### Describe the proposed behavior

There are a few ideas I can think of.

1. Add an extra flag named `--no-override-ui` (or similar) that overrides the data only if it is explicitly declared. It will keep the current behavior and only add that specific use case.
2. Add a special key in the yaml itself that enables the same behavior.
3. In the prefect.yaml, if the keys of `parameters`, `schedules`, etc. are not declared, it will keep the values declared in the UI. Then, if I don't want schedules at all, I explicitly declare it as an empty value (`{}` or `none`) in the yaml. I believe this is the best approach.

### Example Use

How option 3 would look like:
```
deployments:
  - name: deployment-1
    # Because "schedules" key is missing, it will keep the current values.
    entrypoint: flows/hello.py:my_flow
   # Overrides the parameters "number", "message"  and "need_to_override" from the UI. If there are other parameters, they keep the same value that was declared in the UI.
    parameters: 
        number: 42,
        message: Don't panic!
        need_to_override: none
    work_pool:
        name: my-process-work-pool
        work_queue_name: primary-queue
```
