### ISSUE TITLE
Reverse Proxy `URL_PREFIX` connection error

### ISSUE THREAD

**Issue by Pk13055** [PrefectHQ/prefect#18173]
### Bug summary

The `worker` and `deploy` scripts are unable to communicate with the API server (in docker compose with nginx reverse proxy)

Compose file:
```yaml
services:
  ### Prefect Database
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - prefect_network
    volumes:
      - ./data/db:/var/lib/postgresql/data

  ### Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:80
    networks:
      - ui_network
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - server

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:3-python3.12
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://0.0.0.0:8000/prefect
      - PREFECT_API_URL=http://0.0.0.0:8000/prefect/api
      - PREFECT_UI_SERVE_BASE=/prefect
      # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
      #- PREFECT_UI_URL=http://external-ip/prefect
      #- PREFECT_API_URL=http://external-ip/prefect/api
      - PREFECT_SERVER_API_HOST=${PREFECT_SERVER_API_HOST}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      # - EXTRA_PIP_PACKAGES=${EXTRA_PIP_PACKAGES}
    depends_on:
      - database
    networks:
      - ui_network
      - prefect_network

  ### Auto-discovery and deployment service
  deploy:
    image: prefecthq/prefect:3-python3.12
    restart: "no"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
      - "./deployments:/root/deployments"
    environment:
      # - PREFECT_API_URL=${PREFECT_API_URL:-http://0.0.0.0:8000/prefect/api}
      - PREFECT_API_URL=http://0.0.0.0:8000/prefect/api
      - WORK_POOL_NAME=${WORK_POOL_NAME}
      - WORK_POOL_TYPE=${WORK_POOL_TYPE}
    depends_on:
      - server
    networks:
      - ui_network
      - prefect_network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Waiting for Prefect server to be ready...'
        sleep 30
        echo 'Creating work pool...'
        prefect work-pool create $${WORK_POOL_NAME} --type $${WORK_POOL_TYPE} || echo 'Work pool already exists'
        echo 'Deploying flows...'
        cd /root/flows

        # List all Python files for debugging
        echo 'Found Python files:'
        find . -name "*.py" -not -path "./__pycache__/*" | head -10

        # Find all flow functions and deploy them using xargs
        echo 'Discovering and deploying flows...'

        # Create a function to extract flow entrypoints
        extract_flows() {
            for py_file in $$(find . -name "*.py" -not -path "./__pycache__/*"); do
                if grep -q "@flow" "$$py_file"; then
                    # Extract flow function names that follow @flow decorator
                    grep -A 1 "@flow" "$$py_file" | grep "def " | sed 's/def \([^(]*\).*/\1/' | while read flow_func; do
                        if [ ! -z "$$flow_func" ]; then
                            # Output in format: filename:function_name
                            echo "$${py_file#./}:$$flow_func"
                        fi
                    done
                fi
            done
        }

        # Extract all flows and deploy them using xargs
        extract_flows | while read entrypoint; do
            if [ ! -z "$$entrypoint" ]; then
                flow_name=$$(echo "$$entrypoint" | cut -d':' -f2)
                deployment_name="$$flow_name-deployment"

                echo "Deploying: $$entrypoint as $$deployment_name"

                prefect deploy \
                    --name "$$deployment_name" \
                    --pool "$${WORK_POOL_NAME}" \
                    "$$entrypoint" || echo "Failed to deploy $$entrypoint"
            fi
        done
        echo 'Auto-discovery and deployment completed!'

  ## Prefect Worker (Process-based for local execution)
  worker:
    image: prefecthq/prefect:3-python3.12
    restart: always
    entrypoint:
      [
        "/opt/prefect/entrypoint.sh",
        "prefect",
        "worker",
        "start",
        "--pool",
        "${WORK_POOL_NAME}",
        "--type",
        "${WORK_POOL_TYPE}",
      ]
    environment:
      - PREFECT_API_URL=http://0.0.0.0:8000/prefect/api
      # - PREFECT_API_URL=${PREFECT_API_URL:-http://0.0.0.0:8000/prefect/api}
      # - EXTRA_PIP_PACKAGES=${EXTRA_PIP_PACKAGES}
    networks:
      - ui_network
      - prefect_network
    volumes:
      - ./flows:/root/flows
    depends_on:
      - deploy

volumes:
  prefect:

networks:
  ui_network:
  prefect_network:
```
NGINX config:
```nginx
upstream prefect_server {
    server server:4200;
}

# now we declare our main server
server {

    listen 80;
    server_name _;
    client_max_body_size 10M;

    location /prefect/api {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        rewrite ^/prefect/api/?(.*)$ /api/$1 break;
        proxy_pass http://prefect_server;
    }
    location /prefect/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_pass http://prefect_server;
    }
}
```
`.env` vars:
```
COMPOSE_PROJECT_NAME=scheduler
# Database Configuration
POSTGRES_USER=prefect
POSTGRES_PASSWORD=prefect123
POSTGRES_DB=prefect

# Prefect Server Configuration
PREFECT_UI_URL=http://0.0.0.0:8000/prefect
PREFECT_API_URL=http://0.0.0.0:8000/prefect/api
PREFECT_SERVER_API_HOST=0.0.0.0
PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect123@database:5432/prefect

# Work Pool Configuration
WORK_POOL_NAME=default-pool
WORK_POOL_TYPE=process

# EXTRA_PIP_PACKAGES=
```

### Version info

```Text
Version:             3.4.3
API version:         0.8.4
Python version:      3.12.10
Git commit:          1c2ba7a4
Built:               Thu, May 22, 2025 10:03 PM
OS/Arch:             linux/aarch64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.11.5
Integrations:
  prefect-redis:     0.2.2
```
