### ISSUE TITLE
`prefect.deployments.steps.set_working_directory` doesn't work with relative paths

### ISSUE THREAD

**Issue by NicholasPini** [PrefectHQ/prefect#18182]
### Bug summary

I have a deployment that runs on Kubernetes. It depends on a custom Docker container which sets the `WORKDIR` to `/app`. 

In my pull steps, I then clone a repository inside `/app`, which contains a folder `prefect_flow`(note that I do not need to change directory here: the flow starts in the `WORKDIR` as expected) . I need to change directory to this one in order for the flow to work. So, in the pull steps of my deployment, I've set the following step:
```json
{
  "prefect.deployments.steps.set_working_directory": {
    "directory": "prefect_flow"
  }
}
```

But this fails, saying that there is no such file or directory named `prefect_flow`. If I use and absolute path instead (`/app/prefect_flow`) this works as expected.

Here is the weirder part. Looking at [set_working_directory](https://prefect-python-sdk-docs.netlify.app/prefect/deployments/steps/pull/?h=set_work#prefect.deployments.steps.pull.set_working_directory)'s source code, it uses `os.chdir` under the hood. I have written a similar function that looks like this:
```python
def chdir(directory: str | Path, log_result: bool = False):
    os.chdir(directory)
    if log_result:
        print(f"Changed directory to {os.getcwd()}")
```

This function is defined in a local package named `prefect_steps.steps` which is pulled when cloning the repo.

If use this function in my pull steps, like this:
```json
{
  "prefect_steps.steps.chdir": {
    "requires": "prefect-steps>=0.1.0",
    "directory": "prefect_flow"
  }
}
```

everything works as expected: I can pass a relative path to this step and it works. I am not sure why this is the case, it seems to me that these two functions do the same thing.

### Version info

```Text
Version:             3.4.3
API version:         0.8.4
Python version:      3.10.15
Git commit:          1c2ba7a4
Built:               Thu, May 22, 2025 10:00 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.11.5
Integrations:
  prefect-aws:       0.5.10
```

**Comment by yimejky** [comment]
+1, Adding my example to replicate the problem:

deployment:
```yaml
pull:
  - prefect.deployments.steps.git_clone:
      id: clone-step
      repository: https://github.com/<monorepo>.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-token }}'
      directories: ['prefect']
  - prefect.deployments.steps.pip_install_requirements:
      directory: '{{ clone-step.directory }}/prefect'
      requirements_file: worker-requirements.txt
  - prefect.deployments.steps.set_working_directory:
      directory: '{{ clone-step.directory }}/prefect'
```

and the worker scripts:

```bash
prefect worker start --pool basic-worker-pool
```

The pull works as intended because set_working_directory changes the cwd:

source: [prefect/deployments/steps/pull.py](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/deployments/steps/pull.py#L24-L36)
```python
def set_working_directory(directory: str) -> dict[str, str]:
    """
    Sets the working directory; works with both absolute and relative paths.

    Args:
        directory (str): the directory to set as the working directory

    Returns:
        dict: a dictionary containing a `directory` key of the
            directory that was set
    """
    os.chdir(directory)
    return dict(directory=directory)
```

But it also returns the directory that should be used before the flow run:

source: https://github.com/PrefectHQ/prefect/blob/main/src/prefect/flows.py#L2646-L2648

```python
        if output.get("directory"):
            run_logger.debug(f"Changing working directory to {output['directory']!r}")
            os.chdir(output["directory"])
```

where `os.getcwd()` returns already correct working dir:

```text
/private/var/folders/fw/lqlh_4555wg3n6wn7vltyqxw0000gn/T/tmpenibb4msprefect/<monorepo>-main/prefect
```


### My stupid tmp fix

Just add another set_working_directory to current folder to override the `output["directory"]` with "."
```yaml
pull:
  - prefect.deployments.steps.git_clone:
      id: clone-step
      repository: https://github.com/Born-Digital-AI/orchestrator.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-token }}'
      directories: ['prefect']
  - prefect.deployments.steps.pip_install_requirements:
      directory: '{{ clone-step.directory }}/prefect'
      requirements_file: worker-requirements.txt
  - prefect.deployments.steps.set_working_directory:
      directory: '{{ clone-step.directory }}/prefect'
  - prefect.deployments.steps.set_working_directory:
      directory: '.'
```
