### ISSUE TITLE
upgrade to 3.3.4 or beyond fails on large database

### ISSUE THREAD

**Issue by cayspekko** [PrefectHQ/prefect#18263]
### Bug summary

```
server-1         | ERROR:    Traceback (most recent call last):
server-1         |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 692, in lifespan
server-1         |     async with self.lifespan_context(app) as maybe_state:
server-1         |                ~~~~~~~~~~~~~~~~~~~~~^^^^^
server-1         |   File "/usr/local/lib/python3.13/contextlib.py", line 214, in __aenter__
server-1         |     return await anext(self.gen)
server-1         |            ^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/api/server.py", line 632, in lifespan
server-1         |     await run_migrations()
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/api/server.py", line 612, in run_migrations
server-1         |     await db.create_db()
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/interface.py", line 77, in create_db
server-1         |     await self.run_migrations_upgrade()
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/interface.py", line 85, in run_migrations_upgrade
server-1         |     await run_sync_in_worker_thread(alembic_upgrade)
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/utilities/asyncutils.py", line 233, in run_sync_in_worker_thread
server-1         |     result = await anyio.to_thread.run_sync(
server-1         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |         call_with_mark, call, abandon_on_cancel=True, limiter=get_thread_limiter()
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
server-1         |     return await get_async_backend().run_sync_in_worker_thread(
server-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |         func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
server-1         |     return await future
server-1         |            ^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
server-1         |     result = context.run(func, *args)
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/utilities/asyncutils.py", line 243, in call_with_mark
server-1         |     return call()
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/alembic_commands.py", line 36, in wrapper
server-1         |     return fn(*args, **kwargs)
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/alembic_commands.py", line 72, in alembic_upgrade
server-1         |     alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/command.py", line 408, in upgrade
server-1         |     script.run_env()
server-1         |     ~~~~~~~~~~~~~~^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/script/base.py", line 586, in run_env
server-1         |     util.load_python_file(self.dir, "env.py")
server-1         |     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
server-1         |     module = load_module_py(module_id, path)
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
server-1         |     spec.loader.exec_module(module)  # type: ignore
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
server-1         |   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
server-1         |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/_migrations/env.py", line 201, in <module>
server-1         |     run_async_from_worker_thread(apply_migrations)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/utilities/asyncutils.py", line 254, in run_async_from_worker_thread
server-1         |     return anyio.from_thread.run(call)
server-1         |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/from_thread.py", line 59, in run
server-1         |     return async_backend.run_async_from_thread(func, args, token=token)
server-1         |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2510, in run_async_from_thread
server-1         |     return f.result()
server-1         |            ~~~~~~~~^^
server-1         |   File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 456, in result
server-1         |     return self.__get_result()
server-1         |            ~~~~~~~~~~~~~~~~~^^
server-1         |   File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
server-1         |     raise self._exception
server-1         |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2497, in task_wrapper
server-1         |     return await func(*args)
server-1         |            ^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/_migrations/env.py", line 190, in apply_migrations
server-1         |     await connection.run_sync(do_run_migrations)
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py", line 887, in run_sync
server-1         |     return await greenlet_spawn(
server-1         |            ^^^^^^^^^^^^^^^^^^^^^
server-1         |         fn, self._proxied, *arg, _require_await=False, **kw
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
server-1         |     result = context.switch(value)
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/_migrations/env.py", line 159, in do_run_migrations
server-1         |     context.run_migrations()
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~^^
server-1         |   File "<string>", line 8, in run_migrations
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
server-1         |     self.get_context().run_migrations(**kw)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
server-1         |     step.migration_fn(**kw)
server-1         |     ~~~~~~~~~~~~~~~~~^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/prefect/server/database/_migrations/versions/postgresql/2025_04_04_092158_7a73514ca2d6_add_ix_events__event_related_occurred_.py", line 21, in upgrade
server-1         |     op.create_index(
server-1         |     ~~~~~~~~~~~~~~~^
server-1         |         "ix_events__related_gin",
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     ...<3 lines>...
server-1         |         postgresql_using="gin",
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "<string>", line 8, in create_index
server-1         |   File "<string>", line 3, in create_index
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/operations/ops.py", line 998, in create_index
server-1         |     return operations.invoke(op)
server-1         |            ~~~~~~~~~~~~~~~~~^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/operations/base.py", line 441, in invoke
server-1         |     return fn(self, operation)
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/operations/toimpl.py", line 107, in create_index
server-1         |     operations.impl.create_index(idx, **kw)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/ddl/postgresql.py", line 98, in create_index
server-1         |     self._exec(CreateIndex(index, **kw))
server-1         |     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/alembic/ddl/impl.py", line 246, in _exec
server-1         |     return conn.execute(construct, params)
server-1         |            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
server-1         |     return meth(
server-1         |         self,
server-1         |         distilled_parameters,
server-1         |         execution_options or NO_OPTIONS,
server-1         |     )
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 187, in _execute_on_connection
server-1         |     return connection._execute_ddl(
server-1         |            ~~~~~~~~~~~~~~~~~~~~~~~^
server-1         |         self, distilled_params, execution_options
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1527, in _execute_ddl
server-1         |     ret = self._execute_context(
server-1         |         dialect,
server-1         |     ...<4 lines>...
server-1         |         compiled,
server-1         |     )
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
server-1         |     return self._exec_single_context(
server-1         |            ~~~~~~~~~~~~~~~~~~~~~~~~~^
server-1         |         dialect, context, statement, parameters
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
server-1         |     self._handle_dbapi_exception(
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
server-1         |         e, str_statement, effective_parameters, cursor, context
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
server-1         |     raise exc_info[1].with_traceback(exc_info[2])
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
server-1         |     self.dialect.do_execute(
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~^
server-1         |         cursor, str_statement, effective_parameters, context
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
server-1         |     cursor.execute(statement, parameters)
server-1         |     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
server-1         |     self._adapt_connection.await_(
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
server-1         |         self._prepare_and_execute(operation, parameters)
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |     )
server-1         |     ^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
server-1         |     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
server-1         |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
server-1         |     value = await result
server-1         |             ^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
server-1         |     self._handle_exception(error)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
server-1         |     self._adapt_connection._handle_exception(error)
server-1         |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 794, in _handle_exception
server-1         |     raise error
server-1         |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 545, in _prepare_and_execute
server-1         |     self._rows = deque(await prepared_stmt.fetch(*parameters))
server-1         |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
server-1         |     data = await self.__bind_execute(args, 0, timeout)
server-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
server-1         |     data, status, _ = await self.__do_execute(
server-1         |                       ^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |         lambda protocol: protocol.bind_execute(
server-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |             self._state, args, '', limit, True, timeout))
server-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "/usr/local/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
server-1         |     return await executor(protocol)
server-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^
server-1         |   File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
server-1         | TimeoutError
server-1         |
server-1         | ERROR:    Application startup failed. Exiting.
server-1         | Server stopped!
```

docker compose file
```
services:
  server:
    image: prefecthq/prefect:3.4.5-python3.13
    restart: unless-stopped
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]
    environment:
      - PREFECT_UI_API_URL=http://prefect.showpointlabs.com:4200/api
      - PREFECT_LOGGING_SERVER_LEVEL=WARNING
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=${DATABASE_URL}
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
      - PREFECT_STORAGE_S3_BUCKET=my-minio-bucket
      - PREFECT_STORAGE_S3_ACCESS_KEY_ID=secretuser
      - PREFECT_STORAGE_S3_SECRET_ACCESS_KEY=secretkey
      - PREFECT_STORAGE_S3_ENDPOINT_URL=http://minio:9000
      - PREFECT_TASK_RUN_TAG_CONCURRENCY_SLOT_WAIT_SECONDS=3
      - PREFECT_WORKER_QUERY_SECONDS=3
      - PREFECT_WORKER_PREFETCH_SECONDS=5
      - PREFECT_SERVER_DEPLOYMENTS_CONCURRENCY_SLOT_WAIT_SECONDS=3
      - PREFECT_SERVER_TASKS_TAG_CONCURRENCY_SLOT_WAIT_SECONDS=10
    ports:
      - 4200:4200
    depends_on:
      - postgres
      - minio
  worker-docker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.docker-worker
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "worker", "start", "-p", "docker-pool", "--type", "docker"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    scale: 5
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=secretuser
      - MINIO_ROOT_PASSWORD=secretkey
    volumes:
      - "minio:/data"
  postgres:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prefect
volumes:
  prefect:
  postgres_data:
  minio:
```

building these indexes takes awhile for me (about 60 seconds)  (my database is pushing 70 gigs, single postgresql instance without any optimizations)

but the migration times out with the error above

I had to manually apply the indexes
```
DROP INDEX IF EXISTS ix_events__event_related_occurred;
DROP INDEX IF EXISTS ix_events__related_resource_ids;

CREATE INDEX CONCURRENTLY ix_events__related_gin
  ON events USING gin(related);

CREATE INDEX CONCURRENTLY ix_events__event_occurred
  ON events (event, occurred);

CREATE INDEX CONCURRENTLY ix_events__related_resource_ids_gin
  ON events USING gin(related_resource_ids);
```

and then manually updated alembic
```UPDATE alembic_version SET version_num = '7a73514ca2d6';```

probably other ways of getting around it, e.g. dumping the database, maybe more resources etc, but I thought I'd bring it up.

(I went to 3.3.3 to 3.3.4, then on to 3.4.5)

### Version info

```Text
Version:             3.3.3
API version:         0.8.4
Python version:      3.13.2
Git commit:          4100d4ea
Built:               Sat, Apr 05, 2025 01:46 AM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.11.2
Integrations:
  prefect-redis:     0.2.2
```
