### ISSUE TITLE
“Cannot connect to Server API at http://localhost:4200/api” in remote Docker deployment — PREFECT_UI_API_URL ignored

### ISSUE THREAD

**Issue by zs856** [PrefectHQ/prefect#18320]
### Bug summary

When deploying Prefect via Docker Compose on a remote Ubuntu 22.04 server, the Web UI fails to connect to the API—always pointing to localhost, even though PREFECT_UI_API_URL is set:

```Can't connect to Server API at http://localhost:4200/api. Check that it's accessible from your machine.```

### Version info

```Text
prefect version
Error processing line 1 of /opt/conda/envs/prefect/lib/python3.12/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 206, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored


Version:             3.4.6
API version:         0.8.4
Python version:      3.12.11
Git commit:          d10c6e6a
Built:               Wed, Jun 11, 2025 08:03 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         ephemeral
Pydantic version:    2.11.5
Server:
  Database:          postgresql
Integrations:
  prefect-redis:     0.2.2
```

### Additional context

Docker compose file:
```
version: '3'
services:
  postgres:
    image: docker.1ms.run/library/postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd123
      POSTGRES_DB: prefect
    volumes:
      - prefectdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prefect:
    image: docker.1ms.run/prefecthq/prefect:3-python3.12-conda
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:passw0rd123@postgres:5432/prefect
      - PREFECT_SERVER_API_HOST=0.0.0.0                # ❤️ listen on all interfaces
      - PREFECT_UI_API_URL=http://localhost:4200/api   # 🧭 tell UI where API lives
    depends_on:
      - postgres

volumes:
  prefectdb:

```
