### ISSUE TITLE
flow_run|ui_url None is Slack Automations

### ISSUE THREAD

**Issue by mattiamatrix** [PrefectHQ/prefect#18401]
### Bug summary

Hello All,

I have Slack Automations that send a notification to my Slack channels. Since I migrated to Prefect 3, `flow_run|ui_url` is always `None`.

The template is:
```yml
_Flow run_: `{{ flow.name }}/{{ flow_run.name }}`
_State_: *{{ flow_run.state.name }}*
_Timestamp_: {{ flow_run.state.timestamp }}
_Run URL_: {{ flow_run|ui_url }} 
_State message_: {{ flow_run.state.message }}
```

![Image](https://github.com/user-attachments/assets/066047c9-3bd3-4771-b68b-d3c4f859908d)

and the server logs:
```
12:59:21.783 | DEBUG   | prefect.utilities.urls - No UI URL known for this object: flow-run-response
```

I did some debugging and it looks like `flow-run-response` is missing in [UI_URL_FORMATS](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/utilities/urls.py#L30-L43).

Adding the lines below would fix but I am not sure how you want to handle it
```py
"flow-run-response": "runs/flow-run/{obj_id}" 
```

### Version info

```Text
Version:             3.4.7
API version:         0.8.4
Python version:      3.11.12
Git commit:          cd81d15a
Built:               Thu, Jun 26, 2025 09:16 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.11.7
Integrations:
  prefect-gcp:       0.6.8
  prefect-sqlalchemy: 0.5.3
  prefect-aws:       0.5.10
```
