### ISSUE TITLE
Custom docker-compose unexpected logs

### ISSUE THREAD

**Issue by rafal0502** [PrefectHQ/prefect#2715]
### I wrote basic docker-compose file for prefect:

```
version: "3.7"

services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - ./postgres_storage:/var/lib/postgresql/data
    networks:
      - prefect-server
    restart: "always"
    command:
      - "postgres"
      # explicitly set max connections
      - "-c"
      - "max_connections=150"
  hasura:
    image: "hasura/graphql-engine:v1.1.0"
    ports:
      - "3000:3000"
    command: "graphql-engine serve"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgresql://prefect:prefect@postgres:5432/prefect"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_SERVER_PORT: "3000"
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - postgres
  graphql:
    image: "prefecthq/server:latest"
    ports:
      - "4201:4201"
    command: bash -c "prefect-server database upgrade -y && python src/prefect_server/services/graphql/server.py"
    environment:
      PREFECT_SERVER_DB_CMD: "echo 'DATABASE MIGRATIONS SKIPPED'"
      PREFECT_SERVER__DATABASE__CONNECTION_URL: "postgresql://prefect:prefect@postgres:5432/prefect"
      PREFECT_SERVER__HASURA__ADMIN_SECRE: "hasura-secret-admin-secret"
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - hasura
  scheduler:
    image: "prefecthq/server:latest"
    command: "python src/prefect_server/services/scheduler/scheduler.py"
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: "hasura-secret-admin-secret"
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - graphql
  apollo:
    image: "prefecthq/apollo:latest"
    ports:
      - "4200:4200"
    command: "npm run serve"
    environment:
      HASURA_API_URL: "http://hasura:3000/v1alpha1/graphql"
      PREFECT_API_URL: "http://graphql:4201/graphql"
      PREFECT_API_HEALTH_URL: "http://graphql:4201/health"
      PREFECT_SERVER__TELEMETRY__ENABLED: "true"
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - graphql
  ui:
    image: "prefecthq/ui:latest"
    ports:
      - "8080:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__GRAPHQL_URL: "http://localhost:4200/graphql"
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - apollo

networks:
  prefect-server:
    name: prefect-server
```

### An this is in my log:
`graphql_1    | INFO:     172.23.0.6:53114 - "POST /graphql HTTP/1.1" 404 Not Found
apollo_1     | 2020-06-03T19:22:47.256Z { ServerParseError: Unexpected token N in JSON at position 0
apollo_1     |     at JSON.parse (<anonymous>)
apollo_1     |     at /apollo/node_modules/apollo-link-http-common/lib/index.js:35:25
apollo_1     |     at process._tickCallback (internal/process/next_tick.js:68:7)
apollo_1     |   name: 'ServerParseError',
apollo_1     |   response:
apollo_1     |    Response {
apollo_1     |      size: 0,
apollo_1     |      timeout: 0,
apollo_1     |      [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
apollo_1     |      [Symbol(Response internals)]:
apollo_1     |       { url: 'http://graphql:4201/graphql',
apollo_1     |         status: 404,
apollo_1     |         statusText: 'Not Found',
apollo_1     |         headers: [Headers],
apollo_1     |         counter: 0 } },
apollo_1     |   statusCode: 404,
apollo_1     |   bodyText: 'Not Found' } Unexpected token N in JSON at position 0 ServerParseError: Unexpected token N in JSON at position 0
apollo_1     |     at JSON.parse (<anonymous>)
apollo_1     |     at /apollo/node_modules/apollo-link-http-common/lib/index.js:35:25
apollo_1     |     at process._tickCallback (internal/process/next_tick.js:68:7)
apollo_1     | 2020-06-03T19:22:47.256Z 
apollo_1     | Trying again in 3 seconds...
apollo_1     | 
`
Is something missing?
 Previously (before release (0.11.5) there was problem with docker.host.internal behavior

**Comment by joshmeek** [comment]
Hey @rafal0502 I am unable to run this compose file with `docker-compose up`. Is there a reason why you are using a custom docker compose and not running `prefect server start`?

**Comment by rafal0502** [comment]
Hey @joshmeek how does it possible? Do you have error? I wanted to play with it firstly locally and then try it on [kind](https://kind.sigs.k8s.io/docs/user/quick-start/). It easier to create separate pods now

**Comment by joshmeek** [comment]
I'm getting this:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for networks: 'prefect-server'
Unsupported config option for services: 'scheduler'
```

**Comment by rafal0502** [comment]
Ok, I added `version: "3.7"`. Now should work ;-)

**Comment by joshmeek** [comment]
@rafal0502 I can't pinpoint exactly what's wrong with your docker compose file but this one is working for me:

```yaml
version: "3.7"

services:
  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: prefect_server
    networks:
      - prefect-server
    restart: "always"
    command:
      - "postgres"
      # explicitly set max connections
      - "-c"
      - "max_connections=150"
  hasura:
    image: "hasura/graphql-engine:v1.1.0"
    ports:
      - "3000:3000"
    command: "graphql-engine serve"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgresql://prefect:test-password@postgres:5432/prefect_server"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_SERVER_PORT: "3000"
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - postgres
  graphql:
    image: "prefecthq/server:latest"
    ports:
      - "4201:4201"
    command: bash -c "prefect-server database upgrade -y && python src/prefect_server/services/graphql/server.py"
    environment:
      PREFECT_SERVER_DB_CMD: "echo 'DATABASE MIGRATIONS SKIPPED'"
      PREFECT_SERVER__DATABASE__CONNECTION_URL: "postgresql://prefect:test-password@postgres:5432/prefect_server"
      PREFECT_SERVER__HASURA__ADMIN_SECRET: hasura-secret-admin-secret
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - hasura
  scheduler:
    image: "prefecthq/server:latest"
    command: "python src/prefect_server/services/scheduler/scheduler.py"
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: hasura-secret-admin-secret
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - graphql
  apollo:
    image: "prefecthq/apollo:latest"
    ports:
      - "4200:4200"
    command: "npm run serve"
    environment:
      HASURA_API_URL: http://hasura:3000/v1alpha1/graphql
      PREFECT_API_URL: http://graphql:4201/graphql/
      PREFECT_API_HEALTH_URL: http://graphql:4201/health
      PREFECT_SERVER__TELEMETRY__ENABLED: "true"
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - graphql
  ui:
    image: "prefecthq/ui:latest"
    ports:
      - "8080:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__GRAPHQL_URL: http://localhost:4200/graphql
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - apollo

networks:
  prefect-server:
    name: prefect-server

```
