### ISSUE TITLE
Pass private registry creds to Fargate agent (non-programmatic approach)

### ISSUE THREAD

**Issue by oleksandr** [PrefectHQ/prefect#2822]
## Current behavior

I'm trying to execute flows, configured without explicit specification of environment (e.g. `FargateEnvironment`) through the generic agent as specified below:

```yaml
  my-agent:
    image: prefecthq/prefect:${PREFECT_VERSION}
    environment:
      - PREFECT__BACKEND=server
      - PREFECT__SERVER__HOST=http://x.x.x.x
      - PREFECT__LOGGING__LEVEL=DEBUG
      - PREFECT__FLOWS__CHECKPOINTING=true
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...
      - REGION_NAME=eu-central-1
      - containerDefinitions_logConfiguration={"logDriver":"awslogs","options":{"awslogs-group":"npn/prefect","awslogs-region":"eu-central-1","awslogs-stream-prefix":"flow-runs"}}
    restart: always
    command: >
      prefect agent start fargate
        --name my-test-agent
        --show-flow-logs
        -l fargate
        -v
        cpu=256
        memory=512
        executionRoleArn=arn:aws:iam::********:role/ecsTaskExecutionRole
        cluster=npn-ecs1
        networkConfiguration="{'awsvpcConfiguration': {'assignPublicIp': 'DISABLED', 'subnets': ['subnet-*******'], 'securityGroups': ['sg-*******']}}"
```

Everything works as expected excepting pulling image from our private docker registry. The documentation for Fargate and Boto3 suggests to put access token into AWS Secret Manager (done) and pass it in the following structure:

```python
containerDefinitions = {
   "repositoryCredentials": {
        "credentialsParameter":"arn:aws:secretsmanager:eu-central-1:*****:secret:<my secret>"}
}
```

But I couldn't find a way to pass such a parameter via environment variables or **kwargs to agent as CLI parameters.

## Proposed behavior

Would it be possible to add support for credentials in the same way how it works for `containerDefinitions_logConfiguration` or `networkConfiguration`?

E.g.:
```yaml
    environment:
      - PREFECT__BACKEND=server
      - PREFECT__SERVER__HOST=http://x.x.x.x
      - PREFECT__LOGGING__LEVEL=DEBUG
      - PREFECT__FLOWS__CHECKPOINTING=true
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...
      - REGION_NAME=eu-central-1
      - containerDefinitions_logConfiguration={"logDriver":"awslogs","options":{"awslogs-group":"npn/prefect","awslogs-region":"eu-central-1","awslogs-stream-prefix":"flow-runs"}}
      - containerDefinitions_repositoryCredentials={"credentialsParameter":"arn:aws:secretsmanager:eu-central-1:*****:secret:<my secret>"}
```
