### ISSUE TITLE
DaskKubernetesEnvironment expose dask scheduler dashboard

### ISSUE THREAD

**Issue by mgsnuno** [PrefectHQ/prefect#3412]
## Current behavior

`DaskKubernetesEnvironment` doesn't expose the dask scheduler dashboard.

## Proposed behavior

Exposing the dashboard is very useful for debugging and checking the cluster status.

`dask-kubernetes` allows this to happen by setting `dask.config.set({"kubernetes.scheduler-service-type": "LoadBalancer"})`. It creates a service for clients and workers to connect to (https://github.com/dask/dask-kubernetes/issues/259#issuecomment-663085684).

In `DaskKubernetesEnvironment:scheduler_spec_file` I do the following:
```yaml
env:
  - name: DASK_KUBERNETES__SCHEDULER_SERVICE_TYPE
    value: LoadBalancer
  - name: DASK__DISTRIBUTED__COMM__TIMEOUTS__CONNECT
    value: "200"
  - name: DASK__KUBERNETES__DEPLOY_MODE
    value: remote
```
Doesn't work because no LoadBalancer service gets created.
