### ISSUE TITLE
Support for multiple replicas in K8s agent

### ISSUE THREAD

**Issue by laughingman7743** [PrefectHQ/prefect#4845]
## Current behavior

If you set the deployment replicas to 2 or more in the K8s agent, you can have multiple pods, but only one agent will be registered in the server. When a task is executed, the task is duplicated on all pods.

## Proposed behavior

I think that the K8s agent should be registered as an agent on the server in pod units according to replicas. In a production environment, you should be able to configure PodDisruptionBudget and control the minimum number of available pods.

## Example

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
          value: ''
        - name: PREFECT__CLOUD__API
          value: http://prefect-server-1627963707-apollo.default.svc.cluster.local:4200
        - name: NAMESPACE
          value: default
        - name: IMAGE_PULL_SECRETS
          value: 'gcr-image-puller-service-account'
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '[]'
        - name: JOB_MEM_REQUEST
          value: '128Mi'
        - name: JOB_MEM_LIMIT
          value: '128Mi'
        - name: JOB_CPU_REQUEST
          value: '100m'
        - name: JOB_CPU_LIMIT
          value: '100m'
        - name: IMAGE_PULL_POLICY
          value: 'IfNotPresent'
        - name: SERVICE_ACCOUNT_NAME
          value: 'prefect-agent'
        - name: PREFECT__BACKEND
          value: server
        - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
          value: http://:8080
        - name: PREFECT__CLOUD__API_KEY
          value: ''
        - name: PREFECT__CLOUD__TENANT_ID
          value: 'XXXX-XXXX-XXXX-XXXX-XXXX'
        image: prefecthq/prefect:0.15.3-python3.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent
```

**Comment by madkinsz** [comment]
Hey @laughingman7743 - can you explain some more of your use-case here? In theory, agents are light enough that having multiple replicas should be unnecessary.

If you modify the command `prefect agent kubernetes start` to include a `name` that is unique to each replica instance, they will register as distinct agents in the backend.

**Comment by laughingman7743** [comment]
Hi @madkinsz,
I like to have multiple replicas in my production environment so that I don't have downtime for agent. I often use PodDisruptionBudget to set up a configuration where at least one pod is up and running.

In K8s, there are often situations where a pod is evicted due to other pods or node replacements. I would like to know if there is a setting that can eliminate agent downtime, or if it can be improved to support multiple replicas.

**Comment by madkinsz** [comment]
Alright, that makes sense. Adjusting the name should will accomplish what you want; we just need a way to determine that an agent is unique and not a restart of a previously running agent.

**Comment by laughingman7743** [comment]
I see, it would be nice to have a setting in the documentation to prevent agent down in K8s.
However, it is normal for pods to go down in K8s, and it is easy to configure them to recover well from it. I think it would be best to implement agent so that it can be configured for high availability using only K8s settings without such a hack.

**Comment by madkinsz** [comment]
Agents are not designed to be replicated in the way you are describing. We cannot infer if you are restarting an existing agent or spinning up several different ones. The simple solution is to provide a name to clarify your intentions to the system.

I'd recommend using a `StatefulSet` so you can have a consistent pod name / agent ordering so you're not generating a random name each time. This will allow each agent to restart gracefully and receive a consistent ID from Prefect Server while remaining distinct.

See
- https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set
- https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by laughingman7743** [comment]
OK, I'll try StatefulSet.

**Comment by laughingman7743** [comment]
I have tried StatefulSet with the following settings.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
spec:
  serviceName: prefect-agent
  replicas: 2
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
          value: ''
        - name: PREFECT__CLOUD__API
          value: http://prefect-server-1627963707-apollo.default.svc.cluster.local:4200
        - name: NAMESPACE
          value: default
        - name: IMAGE_PULL_SECRETS
          value: 'gcr-image-puller-service-account'
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '[]'
        - name: JOB_MEM_REQUEST
          value: '128Mi'
        - name: JOB_MEM_LIMIT
          value: '128Mi'
        - name: JOB_CPU_REQUEST
          value: '100m'
        - name: JOB_CPU_LIMIT
          value: '100m'
        - name: IMAGE_PULL_POLICY
          value: 'IfNotPresent'
        - name: SERVICE_ACCOUNT_NAME
          value: 'prefect-agent'
        - name: PREFECT__BACKEND
          value: server
        - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
          value: http://:8080
        - name: PREFECT__CLOUD__API_KEY
          value: ''
        - name: PREFECT__CLOUD__TENANT_ID
          value: 'XXXX-XXXX-XXXX-XXXX-XXXX'
        - name: PREFECT__CLOUD__AGENT__NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: prefecthq/prefect:0.15.3-python3.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent
```
It works perfectly. Thank you!
