### ISSUE TITLE
`base_url` not being passed when running `prefect server start`

### ISSUE THREAD

**Issue by igonro** [PrefectHQ/prefect#5375]
Currently when I run `prefect server start` the `base_url` parameter from the `config.toml` is not taken into account. I was trying to use prefect server behing a proxy.

https://github.com/PrefectHQ/prefect/blob/708a4a9ab08ccac3a23033a22c435d94b736129b/src/prefect/cli/server.py#L314-L316

I think this issue will be fixed, with this change:
```python
UI_ENV = dict( 
    APOLLO_URL=config.server.ui.apollo_url,
    BASE_URL=config.server.ui.base_url,
    PREFECT_UI_TAG=ui_version or default_tag,
) 
```

More information in https://github.com/PrefectHQ/prefect/discussions/5376

**Comment by madkinsz** [comment]
Hi! `base_url` isn't an option in our config.

```toml
    [server.ui]
    host = "http://localhost"
    port = "8080"
    host_port = "8080"
    host_ip = "127.0.0.1"
    endpoint = "${server.ui.host}:${server.ui.port}"
    apollo_url = "http://localhost:4200/graphql"
```

Nor is it an environment variable consumed in the compose file

```yaml
  ui:
    image: "prefecthq/ui:${PREFECT_UI_TAG:-latest}"
    ports:
      - "${UI_HOST_IP:-127.0.0.1}:${UI_HOST_PORT:-8080}:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__APOLLO_URL: ${APOLLO_URL:-http://localhost:4200/graphql}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent --head "http://ui:8080/" &> /dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      - apollo
 ```

There's a closed PR that adds the required variables for this https://github.com/PrefectHQ/prefect/pull/4557 — it looks like it needs some more work.
