### ISSUE TITLE
ECS Agent (as a service) fails to receive network configuration on non-default VPCs

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect#5379]
## Description

After deploying the ECS agent using the details specified in this [doc](https://docs.prefect.io/orchestration/agents/ecs.html#running-ecs-agent-in-production) as a ECS service, I continually receive the following error: `ValueError: Failed to infer default networkConfiguration, please explicitly configure using '--run-task-kwargs'`

I have built the service both manually and via the CLI (as documented in the link above) and both result in the same error.  I have also attempted to pass in a `yaml` file stored on s3 with the following defined network configuration:
```
NetworkConfiguration:
  AwsvpcConfiguration:
    Subnets:
      - subnet-xxxx
    SecurityGroups:
      - sg-xxx
    AssignPublicIp: DISABLED
```
as a command argument in the task definition - `prefect,agent,ecs,start,--run-task-kwargs,s3://temp-ecs-test/ecs-config.yaml`

## Expected Behavior
The ECS registered with Prefect Cloud and polling for new work

## Reproduction
The exact steps defined [here](https://docs.prefect.io/orchestration/agents/ecs.html#running-ecs-agent-in-production)

## Environment
This was deployed in a non-default VPC in a `networking-only` ECS cluster

**Comment by kvnkho** [comment]
This was fixed by using changing the casing in the YAML
```
networkConfiguration:
  awsvpcConfiguration:
    Subnets:
      - subnet-xxxx
    securityGroups:
      - sg-xxx
    assignPublicIp: DISABLED
```
