### ISSUE TITLE
Config - host and port is combined incorrectly

### ISSUE THREAD

**Issue by thomafred** [PrefectHQ/prefect#5468]
## Description

When setting the `server` in the config with a path, the `port`-value is appended after the path:

```toml
[server]
host="https://prefect.myhost.com/path/to/apollo"
port=443
```

This results in the `url`-parameter to be set to `https://prefect.myhost.com/path/to/apollo:443` in `prefect.client.Client._send_request`

## Expected Behavior

The `url`-parameter should be set to `https://prefect.myhost.com:443/path/to/apollo` instead

## Reproduction

Use a config of the form below and attempt to deploy a flow:

```toml
[server]
host="https://prefect.myhost.com/path/to/apollo"
port=443
```

## Environment

```
{
  "config_overrides": {
    "logging": {
      "extra_loggers": true
    },
    "server": {
      "host": true,
      "port": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.15.14-100.fc34.x86_64-x86_64-with-glibc2.2.5",
    "prefect_backend": "server",
    "prefect_version": "0.15.3",
    "python_version": "3.8.12"
  }
}
```
