### ISSUE TITLE
Allow `cluster_kwargs` to be provided via config

### ISSUE THREAD

**Issue by multimeric** [PrefectHQ/prefect#5659]
## Current behavior
Currently it is not possible to configure the dask cluster via the config file

## Proposed behavior
We should be able to configure it in this manner:
```toml
[engine.executor.dask]
cluster_class = "dask_jobqueue.SLURMCluster"
cluster_kwargs = {cores = 1, memory = "1 GB"}
```

## Example
This would allow more of the technicalities of execution, which are mostly an environment-specific concern, to be abstracted out from the flow definition. 

For example I want to be able to define a flow once, and for it to run locally using the `LocalDaskExecutor`, but also on HPC using the `DaskExecutor` + `SLURMCluster`, solely using configuration. However at present this isn't really possible since we can't properly configure the cluster without actually changing the flow itself.

## Context
Note how we allow the cluster class to be defined in the config, but not its kwargs:
https://github.com/PrefectHQ/prefect/blob/40e2e2bd1c1de5651bc7fb484c823e43cfc69877/src/prefect/executors/dask.py#L166-L173
