### ISSUE TITLE
Prefect orion kuberenetes-manifest Fails to Find Image

### ISSUE THREAD

**Issue by ColeMurray** [PrefectHQ/prefect#5751]
## Description

When creating a kuberenetes manifest, the current code generates an incorrect / not publicly available docker image.

## Reproduction / Example

```prefect orion kubernetes-manifest```

Observe image 
```
    spec:
      containers:
      - name: api
        image: prefecthq/prefect:dev-python3.8
        command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING"]
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 4200
      - name: agent
        image: prefecthq/prefect:dev-python3.8
        command: ["prefect", "agent", "start", "kubernetes"]
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PREFECT_API_URL
            value: http://orion:4200/api

```

## Error 
The error is generated from here
https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/cli/orion.py#L197
https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/flow_runners.py#L92

where the default image_tag will become dev which does not exist on Dockerhub
https://hub.docker.com/r/prefecthq/prefect

## Fix

A potential fix would be to update "dev" -> "latest"
