### ISSUE TITLE
Kubernetes agent produces mallformed imagePullSecrets field

### ISSUE THREAD

**Issue by mluscon** [PrefectHQ/prefect#6288]
### Bug summary

Kubernetes agent produces its jobs imagePullSecrets field in malformed format:
```
imagePullSecrets:
  - name: map[name:secret_name]
```

Instead of correct:
```
imagePullSecrets:
  - name: secret_name
```

### Reproduction

Use imagePullSecrets in service account, job_template.yaml, or define imagePullSecrets in KubernetesRun.
```
KubernetesRun(image_pull_policy="Always", image_pull_secrets=["secret-name"])
```

```
 get pod prefect-job-df0529a4-6lfhr -o yaml```
```

```
...
spec:
  containers:
  - args:
    - prefect
    - execute
    - flow-run
    env:
    - name: PREFECT__LOGGING__LEVEL
      value: INFO
    - name: PREFECT__BACKEND
      value: server
    - name: PREFECT__CLOUD__AGENT__LABELS
      value: '[]'
    - name: PREFECT__CLOUD__API_KEY
    - name: PREFECT__CLOUD__TENANT_ID
    - name: PREFECT__CLOUD__USE_LOCAL_SECRETS
      value: "false"
    - name: PREFECT__CLOUD__SEND_FLOW_RUN_LOGS
      value: "true"
    - name: PREFECT__CONTEXT__FLOW_RUN_ID
      value: f7bbb8a6-c7cb-4aa4-8aed-bff3c8958c3f
    - name: PREFECT__CONTEXT__FLOW_ID
      value: 13a25f60-f2b1-4760-8718-942bc31e0594
    - name: PREFECT__CONTEXT__IMAGE
      value: xxx
    - name: PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS
      value: prefect.engine.cloud.CloudFlowRunner
    - name: PREFECT__LOGGING__LOG_TO_CLOUD
      value: "true"
    - name: PREFECT__CLOUD__AUTH_TOKEN
    imagePullPolicy: IfNotPresent
    name: test
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prefect-server-serviceaccount-token-qjb7j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: map[name:gitlab-pull-image-secret]
...
```

### Versions
```
docker.io/prefecthq/prefect:1.2.4 
docker.io/prefecthq/prefect:1.2.3
```
