### ISSUE TITLE
Deployment with `azure` block and `docker-container` infra cannot retrieve the flow from the storage

### ISSUE THREAD

**Issue by Trymzet** [PrefectHQ/prefect#6503]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It seems like Prefect is trying to use the local file system as if it were ADL, as well as not using the path defined in the storage block, resulting in  `IsADirectoryError` (`/home/viadot` is the working directory in my container -- I would expect Prefect to be looking for the flow in the basepath defined in my Azure storage block).

### Reproduction

```python
prefect deployment build fake_ingest.py:run \
  -n test_deployment \
  -t dev \
  -q dev \
  -sb azure/my-azure-block \
  -ib docker-container/my-container-block \
  -o deployments/test_deployment.yaml
prefect deployment apply deployments/test_deployment.yaml
prefect agent -q dev
prefect deployment run <FLOW_NAME>/test_deployment
```

### Error

```python
14:48:52.178 | INFO    | prefect.infrastructure.docker-container - Docker container 'organic-bear' has status 'running'
12:48:54.903 | ERROR   | Flow run 'organic-bear' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 246, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 105, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 55, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=None, local_path=".")
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 555, in get_directory
    return await self.filesystem.get_directory(
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 251, in get_directory
    return self.filesystem.get(from_path, local_path, recursive=True)
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 546, in _get
    return await _run_coros_in_chunks(
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 267, in _run_coros_in_chunks
    await asyncio.gather(*chunk, return_exceptions=return_exceptions),
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/adlfs/spec.py", line 1629, in _get_file
    with open(lpath, "wb") as my_blob:
IsADirectoryError: [Errno 21] Is a directory: '/home/viadot/.'
```

### Versions

```
Version:             2.1.1
API version:         0.8.0
Python version:      3.10.6
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             linux/x86_64
Profile:             ***
Server type:         hosted
```

### Additional context

For full picture, I'm also getting the following warning when running `prefect deployment build`. I'll ask somewhere on the forums how to fix it as creating a new block didn't help.
`/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py:573: UserWarning: Block document has schema checksum sha256:cc5fd7bf7e129ced2bf2b25cb0fac04e0c0596464bb5a001c699ddf43d05f752 which does not match the schema checksum for class 'DockerContainer'. This indicates the schema has changed and this block may not load.
  return cls._from_block_document(block_document)`

**Comment by cicdw** [comment]
Hi @Trymzet - could you share the following information so I can investigate a bit deeper:
- whether this reproduces on the latest release
- the contents of `test_deployment.yaml`

Thank you!

**Comment by trybjo** [comment]
Hi, I experience the same issue. But the prefect agent (docker) is able to load the flow script if it stored directly in the blob container (named prefect in this case) . The issue might be related to the way folder functionality is implemented in Azure datalake gen2 compared to AWS S3. And, also the `bucket_path` argument for Azure storage is a bit misleading as mentioned above.

Setup:
- Prefect agent based on prefecthq/prefect:2.3.2-python3.9 running as Azure Container Instance (ACI)
- Azure storage block defined as follows:
```Python
storage = Azure(
    bucket_path="prefect",
    azure_storage_connection_string=conn_str
)
storage.save("prefect")
```
- Build deployment YAML files:
` prefect deployment build flows/healthcheck.py:healthcheck --name health -q dev-queue --storage-block azure/prefect`
`prefect deployment build healthcheck.py:healthcheck_root --name health -q dev-queue --storage-block azure/prefect`

- Local folder structure:
├── flows
│   ├── healthcheck.py
│   ├──__init__.py (empty)
│   └── log_levels_flow.py
├──__init__.py (empty)
├──healthcheck.py
├──healthcheck-deployment.yaml
├──healthcheck_root-deployment.yaml



- File structure in Azure blob container `prefect` after running deployment build commands: 
├── flows
│   ├──__init__.py (empty)
│   └──healthcheck.py
├── __init__.py (empty)
├──healthcheck_root.py


### Deployment with flow script located at root of Azure container (runs just fine)
```YAML
###
### A complete description of a Prefect Deployment for flow 'healthcheck-root'
###
name: health
description: null
version: 5a276c8302490e18630c5f7d8be77666
# The work queue that will handle this deployment's runs
work_queue_name: dev-queue
tags: []
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command:
  - python
  - -m
  - prefect.engine
  stream_output: true
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: healthcheck-root
manifest_path: null
storage:
  bucket_path: prefect
  azure_storage_connection_string: '**********'
  azure_storage_account_name: null
  azure_storage_account_key: null
  _block_document_id: ba1910b3-a57c-4498-932a-33ddb82ea562
  _block_document_name: prefect
  _is_anonymous: false
  _block_type_slug: azure
path: ''
entrypoint: healthcheck.py:healthcheck_root
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
```
![image](https://user-images.githubusercontent.com/40172152/189324988-6db2ad9c-1289-4691-8dfc-f64c9efdb65e.png)

### Deployment with flow script located in `flows` folder of Azure container (fails every time)
```YAML
###
### A complete description of a Prefect Deployment for flow 'healthcheck'
###
name: health
description: null
version: bc67df0fd3d93103af327c9151571ebb
# The work queue that will handle this deployment's runs
work_queue_name: dev-queue
tags: []
parameters: {}
schedule: null
infra_overrides: {}

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: healthcheck
manifest_path: null
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command:
  - python
  - -m
  - prefect.engine
  stream_output: true
  _block_document_id: f1e005e8-1257-4c0a-a123-58546f265f99
  _block_document_name: anonymous-a8313519-6cdb-4b04-9219-d521ae3da5a0
  _is_anonymous: true
  _block_type_slug: process
storage:
  bucket_path: prefect
  azure_storage_connection_string: '**********'
  azure_storage_account_name: null
  azure_storage_account_key: null
  _block_document_id: ba1910b3-a57c-4498-932a-33ddb82ea562
  _block_document_name: prefect
  _is_anonymous: false
  _block_type_slug: azure
path: ''
entrypoint: flows\healthcheck.py:healthcheck
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null

```
![image](https://user-images.githubusercontent.com/40172152/189324046-e394b161-eaad-4e7a-a9d8-fcd4f86ce9e7.png)
