### ISSUE TITLE
Add an official Kubernetes agent template

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6726]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, `prefect kubernetes manifest` only provides manifest for orion and flow-run-job. 

### Describe the proposed behavior

It would be great to have an official template for Cloud agents deployable to Kubernetes.

```
prefect kubernetes manifest agent
```

Example template we could use:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: prefecthq/prefect:2-python3.10
          command: ["prefect", "agent", "start", "-q", "default"]
          imagePullPolicy: "IfNotPresent"
          env:
            - name: PREFECT_API_URL
              valueFrom:
                secretKeyRef:
                  name: your_k8s_secret_name
                  key: api-url
            - name: PREFECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: your_k8s_secret_name
                  key: api-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-blocks-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-blocks-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: infra-blocks
  apiGroup: rbac.authorization.k8s.io
```
