### ISSUE TITLE
Better Enums parameters

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7119]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If you currently define a parameter of a flow as a type Enum, Orion will show the value instead of the name.

```
class Color(Enum):
    RED = 1
    GREEN = 2


@flow
def do_it(data: Color) -> None:
    ...
```

<img width="800" alt="image" src="https://user-images.githubusercontent.com/24698503/194914415-5ff0a4f7-3227-4a82-8b08-2819e5ab44d1.png">

### Describe the proposed behavior

I use enums because i want to give names to values. Showing (only) the value makes the whole exercise of supporting enums somewhat pointless.

Showing the name is a much better idea - the value can be shown as an option but this is quite unimportant

![image](https://user-images.githubusercontent.com/24698503/194920581-80c82f9b-90d7-409f-b699-a7b3bc370cd3.png)

### Additional context

This will require an modification of how enums are stored in the parameter_openapi_schema

Defintions:
```yaml
Color:
  title: Color
  description: An enumeration.
  enum:
  - 1
  - 2
```
to a oneOf based soliton  [src](https://stackoverflow.com/questions/66465888/how-to-define-enum-mapping-in-openapi) 

```yaml
Color:
  title: Color
  type: integer
  oneOf:
    - title: RED
      const: 1
    - title: GREEN
      const: 2
```
or some openapi_schema extension  [src](https://stackoverflow.com/questions/66465888/how-to-define-enum-mapping-in-openapi) 

```yaml
Color:
  title: Color
  description: An enumeration.
  enum:
  - 1
  - 2
  x-enumNames: [RED, GREEN]
```

which might be much easier to implement
