### ISSUE TITLE
allow_failure() doesn't work on KubernetesJob() infrastructure

### ISSUE THREAD

**Issue by david-elliott-deliveroo** [PrefectHQ/prefect#7346]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The `allow_failure()` wrapper seems to have no effect for a flow deployed using `KubernetesJob` infrastructure, tested with both the `SequentialTaskRunner` and `ConcurrentTaskRunner`.

When I run the same flow locally it works as expected (downstream tasks are ran), but when it’s ran on k8s it ignores the wrapper and the downstream tasks just go to NotReady as if the allow_failure() wrapper weren’t there at all.

### Reproduction

```python3
# Prefect version 2.6.1

from prefect import flow, task, allow_failure, get_run_logger
from prefect.task_runners import ConcurrentTaskRunner
import time

@task()
def sql_task(task_name: str):
    logger = get_run_logger()
    logger.info(f"RUNNING: {task_name}")
    time.sleep(3)
    if task_name == "task_2":
        raise Exception("failed task")

@flow(name="demo_11", task_runner=ConcurrentTaskRunner())
def demo_11():
    logger = get_run_logger()
    logger.info(f"Flow now starting")
    task_1 = sql_task.with_options(name='task_1').submit(task_name='task_1', wait_for=[])
    task_2 = sql_task.with_options(name='task_2').submit(task_name='task_2', wait_for=[allow_failure(task_1)])
    task_3 = sql_task.with_options(name='task_3').submit(task_name='task_3', wait_for=[allow_failure(task_2)])

if __name__ == "__main__":
    demo_11()
```

### Error

In the above MRE, task_3 isn't ran when deployed on k8s (the flow ends immediately after task_2 fails, and task_3 ends in a `NotReady` state. 

When running locally, `task_2` ends in `Failed` state, and then `task_3` runs to completion (as is the expected behaviour of `allow_failure()`.

### Versions

```Text
2.6.1
```

### Additional context

Flow was deployed with the following deployment file: 
```yaml
###
### A complete description of a Prefect Deployment for flow 'demo_11'
###
name: demo_11
description: null
version: 61ce79ad960d3a0a148fc7e19def1f31
# The work queue that will handle this deployment's runs
work_queue_name: test-kubernetes
tags: []
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command: null
  image: xxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/foo-repo:p2-k8s-v0.0.41
  namespace: prefect2
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: 5
  pod_watch_timeout_seconds: 60
  stream_output: true
  finished_job_ttl: 300
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: demo_11
manifest_path: null
storage: null
path: /app
entrypoint: workflows/demo_11.py:demo_11
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
```

Specifically, the flow was added to a docker image which built and pushed to ECR, and then I deployed a k8s agent with that same ECR docker image which listens for flow runs and creates k8s jobs per the KubernetesJob infra. As such, the "storage" is null i.e. it's local, because the flow (and all requirements / prefect etc) is already stored in the docker image that's deployed on k8s, and when the k8s job spawns a new pod, it runs with this same ECR image.
