### ISSUE TITLE
Using `task_input_hash` in containerized flow runs fails to find cached results

### ISSUE THREAD

**Issue by jpidugu** [PrefectHQ/prefect#8637]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using Prefect's `task` caching in ephemeral infrastructure (e.g. a Kubernetes Pod or a Docker Container), you cannot use the out-of-the-box `task_input_hash` function safely, as there is no infrastructure-identifying input used in the `task_input_hash` function. This means that this snippet in the [caching section of the docs](https://docs.prefect.io/concepts/tasks/#caching):

> Task results are cached in memory during a flow run and persisted to the location specified by the PREFECT_LOCAL_STORAGE_PATH setting. As a result, task caching between flow runs is currently limited to flow runs with access to that local storage path.

should likely warn that you **must** implement. your own `cache_key_fn` in ephemeral infrastructure in order to utilize task caching. Without a customized cache function, you will run into

```
Crash detected! Execution was interrupted by an unexpected exception: ValueError: Path /root/.prefect/storage/6ee24b2ce91d4d56a49af73e86f50c2f does not exist.
```

in any flow runs that have a cache hit on a task that was cached by another flow run running in a different location.

Additionally, Prefect does not fall back to re-computing the task results if the cached data is not found in the local filesystem. More specifically, when the `PREFECT_LOCAL_STORAGE_PATH` exists, but the cached data does not exist within it, the flow run will crash. This is captured in https://github.com/PrefectHQ/prefect/issues/6086.

Ideally, the solution here would be to fix the failure of "missing cached data", and provide clearer guidance to the requirements of using caching in environments where the stored data is not present.

As a solution for Kubernetes, you can use the [Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) to provide the Pod UID as an environment variable, and use that as an input into a custom cache function.

The change to the `deployment.yaml`:
```yaml
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_UID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
```

The customized cache function:
```python
import os
from typing import Any
​
from prefect.context import TaskRunContext
from prefect.utilities.hashing import hash_objects

def custom_cache_key_fn(
    context: TaskRunContext, arguments: dict[str, Any]
) -> str | None:
    return hash_objects(
        context.task.task_key,
        context.task.fn.__code__.co_code.hex(),
        os.getenv("POD_UID", "NO_POD_UID_SPECIFIED"),
        arguments,
    )
```

### Reproduction

Note: this will pass successfully in a local environment, and *must* be run in a kubernetes pod/docker container to see the failure.

```python3
@task(cache_key_fn=task_input_hash, cache_expiration=timedelta(minutes=5))
def my_cached_task():
    return random.random()

def my_flow():
    my_cached_task.submit()

if __name__ == "__main__":
    run_deployment('my_flow')
    run_deployment('my_flow')  # will fail if executed in a different container
```

### Error

```python3
Crash detected! Execution was interrupted by an unexpected exception: ValueError: Path /root/.prefect/storage/6ee24b2ce91d4d56a49af73e86f50c2f does not exist.
```

### Versions

```Text
Version:             2.8.0
API version:         0.8.4
Python version:      3.10.2
Git commit:          50f0ad0a
Built:               Thu, Feb 9, 2023 3:38 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0
```

### Additional context

https://github.com/PrefectHQ/prefect/issues/7646 is another issue that discusses adding additional types of `cache_key_fn` out of the box, if this is the solution, this may be worth adding as a standard solution.
