### ISSUE TITLE
Structured logging option for worker

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/prefect#9197]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

At the moment, we log human-readable text output to standard error. In Google Cloud Logging (Stackdriver), [both the stderr and stdout streams are collected from running containers](https://cloud.google.com/blog/products/management-tools/using-logging-your-apps-running-kubernetes-engine). Log messages output to stdout are treated as INFO level and log messages output to stderr are treated as ERROR level.

This means that log messages that we write at INFO level to stderr (appears to be all logs) will appear as errors in Stackdriver, and cannot be filtered easily.

We support [various settings to control logging behavior](https://docs.prefect.io/latest/concepts/settings/#logging-settings) including choosing a formatter, [customizing log formatting](https://docs.prefect.io/latest/concepts/logs/), and setting various configuration flags to control log output.

### Describe the proposed behavior

This proposes adding a built-in handler (or documenting a handler if it already exists) that outputs log messages in structured (JSON) format. Stackdriver will then parse and ingest the JSON, making it searchable. [Stackdriver supports many common field names](https://cloud.google.com/logging/docs/structured-logging) and we likely will not need any customization beyond emitting messages as JSON.

### Example Use

Users could set a configuration flag like: `PREFECT_LOGGING_JSON=True` or `PREFECT_LOGGING_TYPE=json`

### Additional context

I'm not sure what the default should be -- the tradeoff is either something easier to view in `kubectl logs` or Stackdriver. I'd lean toward keeping the default behavior (logging text) but this is not a strong opinion. We should ensure that we are logging `info` level logs to `stdout` and `warning`/`error` logs to `stderr`, however.

**Comment by rpeden** [comment]
I did a writeup on JSON logging to a file here: https://discourse.prefect.io/t/how-to-stream-prefect-logs-to-a-file/1963

Would that do what you need? Maybe the docs would be a better place for instructions like this - it would be much more discoverable.

**Comment by jawnsy** [comment]
That's really awesome @rpeden! I think moving something like this to the docs would make sense, since I'd expect it to be a relatively common task for administrators.

I also think adding a value to our Helm chart so we can turn it on easily would make sense (and would also help make this more discoverable as well)

**Comment by rpeden** [comment]
Also worth noting that Python's built-in log handlers log _everything_ to `stderr` by default, and since PrefectConsoleHandler subclasses `logging.StreamHandler`, it inherits that behavior.

You can make the console log output go to stdout by using a custom `logging.yml` as described in my Discourse post, but instead of adding a new handler you can just add one line to the existing `console` handler: `stream: ext://sys.stdout`. So that section of `logging.yml` would look like:

```yaml
handlers:

    # The handlers we define here will output all logs they receieve by default
    # but we include the `level` so it can be overridden by environment

    console:
        level: 0
        class: prefect.logging.handlers.PrefectConsoleHandler
        formatter: standard
        stream: ext://sys.stdout
        styles:
            log.web_url: bright_blue
            log.local_url: bright_blue

            log.info_level: cyan
            log.warning_level: yellow3
            log.error_level: red3
            log.critical_level: bright_red

            log.completed_state: green
            log.cancelled_state: yellow3
            log.failed_state: red3
            log.crashed_state: bright_red

            log.flow_run_name: magenta
            log.flow_name: bold magenta
```
