### ISSUE TITLE
Load project variables from environment for CI/CD 

### ISSUE THREAD

**Issue by rizziemma** [PrefectHQ/prefect#9238]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, there are two options to not hard-code values in `prefect.yaml` and `deployment.yaml` : blocks and step outputs, which are both configured manually before running the deploy command.

### Describe the proposed behavior

A new option would be to load values from environment variables (or perhaps from new CLI parameters) to provide runtime generated variables.

### Example Use

For example, setting the image tag of a dockerized build by loading a environment variable:

```
build:
- prefect_docker.projects.steps.build_docker_image:
    requires: prefect-docker>0.1.0
    image_name: my-image/orion
    tag: '{{ $CUSTOM_TAG }}'
```
This custom tag can be generated at runtime to provide a new tag at each pipeline, especially usefull for CI/CD builds.

### Additional context

Current work around (any simpler solution is welcomed too!) is I override the tag in the file during the CI/CD pipeline.
