### ISSUE TITLE
Update yaml files to conform with common yaml linting standards

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect#9245]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently `prefect project init` generates two yaml files (deployment.yaml & prefect.yaml). These files "as is" will be flagged in any generic yaml linter (like [yamllint](https://yamllint.readthedocs.io/en/stable/)):
```
prefect.yaml
  4:1       warning  missing document start "---"  (document-start)
  10:81     error    line too long (91 > 80 characters)  (line-length)
  13:81     error    line too long (94 > 80 characters)  (line-length)
  15:1      error    wrong indentation: expected 2 but found 0  (indentation)
```

### Describe the proposed behavior

Any generated yaml files should confirm with common yaml standards to avoid being flagged by end-users ci pipelines. Specifically, there should be indents on lists and lines should not exceed 80 chars:
```
# File for configuring project / deployment build, push and pull steps

# Generic metadata about this project
name: test
prefect-version: 2.10.4

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to
# remote locations
push: null

# pull section allows you to provide instructions for cloning this project in
# remote locations
pull:
  - prefect.projects.steps.git_clone_project:
      repository: git@github.com:PrefectHQ/test.git
      branch: main
      access_token: null
```
