### ISSUE TITLE
Propagate output of steps to all downstream steps in Prefect project

### ISSUE THREAD

**Issue by sugibuchi** [PrefectHQ/prefect#9346]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Outputs of steps in a Prefect project are propagated to only steps in `pull` section.

### Describe the proposed behavior

Outputs of steps in a Prefect project are propagated to all steps including `build` and `pull` section.

This behavior can be implemented like below:

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/root.py#L437-L440
```
    ## RUN BUILD AND PUSH STEPS
    step_outputs = {}
    for step in project["build"] + project["push"]:
        step = apply_values(step, step_outputs)        # <-- new!
        step_outputs.update(await run_step(step))
```

### Example Use

```
push:
  - my_prefect_utils.projects.steps.git_info: {}
      requires: my-prefect-utils>=0.1.0
  - prefect_aws.projects.steps.push_project_to_s3:
      requires: prefect-aws>=0.3.0
      bucket: my-bucket
      folder: {{ git_repo_name_slug }}-{{ git_ref_slug }}
      credentials: null

pull:
  - prefect_aws.projects.steps.pull_project_from_s3:
      requires: prefect-aws>=0.3.0
      bucket: my-bucket
      folder: "{{ folder }}"
      credentials: null
```

`my_prefect_utils.projects.steps.git_info` is our custom step outputting information of the current Git repository like `git_repo_name_slug` and `git_ref_slug`.

We want to propagate these values to the downstream `push` step to automatically determine location of the folder to upload flow codes.

### Additional context

We may have similar use cases propagating outputs from steps in `build` section to subsequent sections.

The current behavior (propagate to only `pull` section) is a bit confusing and not convenient to chain multiple steps in different sections.
