### ISSUE TITLE
Unable to deploy a flow with version 2.10.6

### ISSUE THREAD

**Issue by RochaOwng** [PrefectHQ/prefect#9371]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm trying to deploy a flow and facing this error:

`'NoneType' object has no attribute 'get'`

This is happening with the last update (2.10.6)

I can run the flow through python3 flow.py as you can see below:
![image](https://user-images.githubusercontent.com/27255269/235213247-708ecbd5-890b-4019-9e7f-90aa038ab651.png)

Downgrading the version I'm able to do normally.

### Reproduction

```python3
prefect deploy alocacao/alocacao_predictions.py:main_pred -n alocacao-pred-deploy -p alocacao-work
```

### Error

```python3
'NoneType' object has no attribute 'get'
```

### Versions

```Text
Version:             2.10.6
API version:         0.8.4
Python version:      3.11.3
Git commit:          d7a8f6bf
Built:               Thu, Apr 27, 2023 2:23 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
```

**Comment by desertaxle** [comment]
Thanks for opening an issue @RochaOwng! Can you share the contents of your `deployment.yaml` to help me reproduce this issue?

**Comment by RochaOwng** [comment]
Hey @desertaxle!

My deployment.yaml is the default one. Didn't change anything

```
# base metadata
name: null
version: null
tags: []
description: null
schedule: null

# flow-specific fields
flow_name: null
entrypoint: null
path: null
parameters: {}
parameter_openapi_schema: null

# infra-specific fields
work_pool:
  name: null
  work_queue_name: null
  job_variables: {}
```
