### ISSUE TITLE
Github Submodule does not get clone with Prefect 2.10.9

### ISSUE THREAD

**Issue by akmukherjee** [PrefectHQ/prefect#9555]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have abug report for Submodules initialization in Prefect Projects. Currently my prefect.yaml looks as shown below:

```
# Generic metadata about this project
name: icdc-dataloader
prefect-version: 2.10.9

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.projects.steps.git_clone_project:
    repository: https://github.com/akmukherjee/prefect-test
    branch: main
    include_submodules: true
  
```
This set up does not pull the submodules associated with this repo.  This is **really easy** to reproduce and I have reproduced it in my code [here ](https://github.com/akmukherjee/prefect-test) and this has been discussed [here](https://github.com/PrefectHQ/prefect/issues/9462) and merged [here](https://github.com/PrefectHQ/prefect/pull/9504).

### Reproduction

```python3
# Generic metadata about this project
name: icdc-dataloader
prefect-version: 2.10.9

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.projects.steps.git_clone_project:
    repository: https://github.com/akmukherjee/prefect-test
    branch: main
    include_submodules: true
  
```

### Error

Please see the screenshots here: https://github.com/PrefectHQ/prefect/issues/9462

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.8.3
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```
