### ISSUE TITLE
Parameter descriptions in deployment.yaml do not keep newlines when parsing docstring

### ISSUE THREAD

**Issue by Wingmore** [PrefectHQ/prefect#9622]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It's pretty cool how the parameter descriptions in a deployment yaml is automatically generated from a function docstring. However if the variable description spans more than one line, then the description does not continue on as well.

For example, in my flow docstring I have this:
![image](https://github.com/PrefectHQ/prefect/assets/36834195/d7f57f6c-8734-4bbb-9629-353bbb7ae3bc)

However after running `prefect deployment build` the second line is missing...
![image](https://github.com/PrefectHQ/prefect/assets/36834195/8de9da91-0c2d-47b3-a8c8-6ede6d67925a)

### Reproduction

```python3
def get_outdated_files(
    config_path: Path = Path("./config.yaml"),
    no_download: bool = False,
):
    """Run with the options specified in config.yaml

    Args:

        config_path: (default config.yaml).

        no_download: (default False) Will NOT automatically update and download
        files if set to True.
"""
...
```

### Error

```python3
Missing second line (or more) from deployment yaml.
```

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.10.8
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by billpalombi** [comment]
Thank you for bringing this to our attention @Wingmore! We'll address this at the nearest opportunity.

**Comment by serinamarie** [comment]
Hi @Wingmore, I am unable to reproduce your issue on 2.10.11. When running the following steps on the latest version of Prefect, does the issue still occur for you?

1. Deploy the following flow:

```python
from prefect import flow

@flow
def hello_world(
):
    """Run with the options specified

    Args:

        a: A single line of code.

        b: This argument is a multi-line string. It will be
        displayed in the deployment.yaml file fully.
"""
    pass

if __name__ == "__main__":
    hello_world()
```
2. Run the following command: 
```bash
prefect deployment build my_flow.py:hello_world --name 'test-deployment'
```
3. View `deployment.yaml`
```yaml
###
### A complete description of a Prefect Deployment for flow 'hello-world'
###
name: test-deployment
description: |-
  Run with the options specified

  Args:

      a: A single line of code.

      b: This argument is a multi-line string. It will be
      displayed in the deployment.yaml file fully.
version: 6646e2d4880c1a61e264f11d2d28efc7
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
tags: []
parameters: {}
schedule: null
is_schedule_active: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  block_type_slug: process
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: hello-world
manifest_path: null
storage: null
path: /Users/bean/prefect-demo/boyd
entrypoint: boyd.py:hello_world
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
timestamp: '2023-05-30T20:19:12.904415+00:00'
```

**Comment by Wingmore** [comment]
Hi @serinamarie, thanks for the reply.
It is not the docstring but the parameters descriptions that is missing the second line. So if you add `a` and `b` into the function arguments like so: 

```
from prefect import flow

@flow
def hello_world(
    a,
    b,
):
    """Run with the options specified

    Args:

        a: A single line of code.

        b: This argument is a multi-line string. It will be
        displayed in the deployment.yaml file fully.
"""
    pass

if __name__ == "__main__":
    hello_world()

``` 

then the parameter description gets generated missing the second line for argument `b` (even though the main description is ok):

```
###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: hello-world
manifest_path: null
storage: null
path: /home/adam/Atmo/storage/Edwin/prefect-pipeline-scratch/deployment_tutorial
entrypoint: 2lin_description_test.py:hello_world
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    a:
      title: a
      description: A single line of code.
      position: 0
    b:
      title: b
      description: This argument is a multi-line string. It will be
      position: 1
  required:
  - a
  - b
  definitions: null
```
