### ISSUE TITLE
Allow users to define a workspace (and/or profile) in `deployment.yaml`

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect#9649]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, if your `deployment.yaml` file contains deployments that map to different workspaces, you have to deploy separately, switching workspaces between each `prefect deploy` command or by having separate CI workflows that handle each workspace-deployment individually. 

### Describe the proposed behavior

Allow a profile-like definition at the deployment level that could enable users to run `prefect deploy --all` (abbreviated):
```yaml
  - name: Deployment 1
    profile:
      workspace: dev
      api_key: {{ DEV_API_KEY }}

  - name: Deployment 2
    profile:
       workspace: prd
       api_key: {{ PRD_API_KEY }}
```

Also, allow workspace definition at the `prefect.yaml` level, as well as continuing to allow for inferring from the users `cat ~/.prefect/profiles.toml`
