### ISSUE TITLE
Add `run_shell_script` project step

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9783]
### Summary

Add a step named `run_shell_script` that runs a user-defined script as part of a deployment lifecycle. Should support templating of variables and secret blocks to enable the parameterization provided scripts.

### Example Usage

Run a script declared in line:
```yaml
pull:
    prefect.projects.steps.git_clone_project:
        repository: https://github.com/org/repo
    prefect.projects.steps.run_shell_script:
        script: |
             echo 'Pulling config...'
             curl https://example.com/config.json
             echo 'Successfully pulled config!'
        directory: {{ directory }}
```

Run a script declared in a file:
```yaml
pull:
    prefect.projects.steps.git_clone_project:
        repository: https://github.com/org/repo
    prefect.projects.steps.run_shell_script:
        script: bash path/to/my_script.sh
        directory: {{ directory }}
```
