### ISSUE TITLE
prefect.projects.steps.git_clone_project should be able to pull from commit id

### ISSUE THREAD

**Issue by NicholasFiorentini** [PrefectHQ/prefect#9784]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, it is possible to pull from GitHub repositories by branch using the proper `pull` step in a project:

```yaml
pull:
  - prefect.projects.steps.git_clone_project:
      repository: https://github.com/org/repo.git
      branch: main
```

### Describe the proposed behavior

For reproducibility and accountability, I would be able to specify the exact git commit instead of the generic branch.

### Example Use

```yaml
pull:
  - prefect.projects.steps.git_clone_project:
      repository: https://github.com/org/repo.git
      reference: <commit-id>
```
