### ISSUE TITLE
Support deploying by name with multiple deployments having the same name

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9913]
Suppose I have the following `deployments.yaml`:

```yaml
deployments:
- name: "default"
  entrypoint: "flows/hello.py:hello"

- name: "default"
  entrypoint: "flows/hello.py:hello_parallel"
```

There are two different flows, `hello` and `hello-parallel`, each of which has one deployment called `default`. In this scenario, running `prefect deploy --all` will deploy both, but running `prefect deploy -n default` will only deploy the first one. In the second case, we should either surface an error, or preferably support deploying both with something like `prefect deploy -n flow-name/deployment-name`.
