### ISSUE TITLE
"prefect deploy --all --ci" still prompts when there are more than 2 deployments in the deployment.yaml file

### ISSUE THREAD

**Issue by tanderson-hp** [PrefectHQ/prefect#9926]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running `prefect deploy --all --ci` with more than 1 deployment defined in the Deployment.yaml file, the cli still prompts for creating a schedule. See example yaml below:

```yaml
deployments:
- name: etl-deployment
  version: 1
  tags: ['etl']
  schedule: null
  description: "Run DB ETL Job"
  entrypoint: flows/etl_flow.py:trigger_etl_flow
  work_pool:
    name: default-prefect-process-pool
- name: etl-deployment2
  version: 1
  tags: ['etl']
  schedule: null
  description: "Run DB ETL Job2"
  entrypoint: flows/etl_flow.py:trigger_etl_flow
  work_pool:
    name: default-prefect-process-pool
```

### Reproduction

```python3
1. Create a sample flow
2. Create a deployments.yaml file with 2 deployments without configured schedules (see above for example)
3. Execute `prefect deploy --all --ci`
```

### Error

```python3
N/A - Unexpected behavior via prompt. Below prompt is shown:

`? Would you like to schedule when this flow runs? [y/n] (y):`
```

### Versions

```Text
Version:             2.10.13
API version:         0.8.4
Python version:      3.11.0
Git commit:          179edeac
Built:               Thu, Jun 8, 2023 4:10 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```
